### ISSUE TITLE
Using deprecated functions

### ISSUE THREAD

**Issue by zlanich** [react-grid-layout/react-draggable#104]
Hey there, after being forced to update some modules for compatibility reasons, I noticed that the console yells about react-draggable using deprecated FindDOMNode at draggable.js:481:
- [Error Screenshot](http://drop.zachlanich.com/QEKh)
- [Code Screenshot](http://drop.zachlanich.com/14pu7)

Are there any plans to update this? Thanks.

**Comment by timkrins** [comment]
Already pull requests that fix this. #102

**Comment by STRML** [comment]
This is fixed in `v1.0.0`.
