### ISSUE TITLE
 Cannot resolve ./lib/Draggable

### ISSUE THREAD

**Issue by jardakotesovec** [react-grid-layout/react-draggable#105]
Just updated to version 1.0.0. I am using webpack and I end up with error

```
ERROR in ./~/react-draggable/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/Draggable in /.../node_modules/react-draggable
 @ ./~/react-draggable/index.js 1:17-43
```

in lib folder there are files

```
Draggable.es6
DraggableCore.es6
```

The extension seems to be unusual.

**Comment by STRML** [comment]
Thanks, must be a loader issue - I'll resolve asap.

**Comment by STRML** [comment]
Are you explicitly loading `index.js`? Webpack should be using the `"main"` config which exports a umd build compatible with any ES5 environment.

**Comment by jardakotesovec** [comment]
```
const Draggable = require('react-draggable');
```

And using latest webpack 1.12.2.

package.json says to use `dist/react-draggable.js`, but there is no dist folder in npm package.

**Comment by STRML** [comment]
Ah that's the issue. Thanks.

**Comment by STRML** [comment]
Try `v1.0.1`.

**Comment by jardakotesovec** [comment]
@STRML thanks, that helped.
