### ISSUE TITLE
Documentation on how to snap or animate an element back to it's initial position?

### ISSUE THREAD

**Issue by dey-dey** [react-grid-layout/react-draggable#106]
I tried clearing the element's transform css property, but then the next time I drag it the start position is off.
![untitled-2](https://cloud.githubusercontent.com/assets/796926/10857655/bffdff98-7f25-11e5-9598-cc9814256636.gif)
A quick example would be great!

**Comment by julienvincent** [comment]
Did you manage to solve this?

**Comment by STRML** [comment]
Don't manipulate CSS directly. You have to reset the position via props. Use `<Draggable>`'s position property or `<DraggableCore>`.

**Comment by kevinmamaqi** [comment]
Any example using position property + animation? I manage to update the position successfully, but I am stuck with the animation to come back smoothly via CSS transitions or other methods.

**Comment by maxvia37** [comment]
Hello @kevinmamaqi! I have the same issue. Did you manage to implement the animation to come back smoothly via CSS transitions?
