### ISSUE TITLE
Fractionary transform: translate in chrome

### ISSUE THREAD

**Issue by queimadus** [react-grid-layout/react-draggable#108]
Using fractionary values on `transform: translate(x, y)` on a draggable element which has a child with a property that forces hardware acceleration will result in a fuzzy element in Chrome `46.0.2490.80 (64-bit)`.

Here is a simplified example:
https://jsfiddle.net/wtvdq4ep/

Would you consider adding a flag that rounds these values?

**Comment by STRML** [comment]
Sorry, that fiddle doesn't work.

**Comment by queimadus** [comment]
Doesn't work in what sense?

**Comment by STRML** [comment]
Ah. I thought you were trying to show a `<Draggable>`.

In any case, I don't see it blurred. And in normal usage, the Draggable would never hit fractional coordinates.

If you need more specialized behavior, use `<DraggableCore>`.

**Comment by queimadus** [comment]
I'm adding this issue here since I think the fix should be added at this level, but I experienced it in the `react-grid-layout` project.

In that setup I get fractional values when the element is idle (Although I never get fractionals as the element is being dragged).

**Comment by STRML** [comment]
That would be a fix in RGL then, which will be using DraggableCore.

**Comment by queimadus** [comment]
You're right. The problem is completely ortogonal to `Draggable`. I'll add the issue in RGL.

Btw, the issue is mitigated if you you're using a retina display; in non-retina monitors, the fuzzy text is evident.
