### ISSUE TITLE
you can't update the start positions on the axis the DraggableCore is allowed to move

### ISSUE THREAD

**Issue by talkhot** [react-grid-layout/react-draggable#109]
If you wanne update the Draggable(Core) elements position, for instance if you want the element to get back to its start position when dragging ends, you can only set the position of the opposite axis you would like to update. So I would like to be able to drag only the x axis and update the x postion on state change. In version v0.8.5 this functions still like you expected, but in version 1.0.1 it acs like shown below (you can't change the axis you drag).

```
axis='x'
start={ { x: (you can not dynamically change position), y: (here you can) } }

// or in my use case I want to set the x position basted on the state. The elm won't update now on state change. 
axis='x'
start={ { x: this.state.xPos, y: 0 } }

now it will but shouldn't
axis='y'
start={ { x: this.state.xPos, y: 0 } }
```

**Comment by josdeweger-zz** [comment]
I ran into the same issue. I fixed it locally by setting the state.clientX and state.clientY on componentWillReceiveProps like this:

``` javascript
this.componentWillReceiveProps = function(nextProps) {
   _this.setState({
      clientX: nextProps.start.x
      clientY: nextProps.start.y
   });
}
```

Did not create a PR though, can't get the Makefile to work on Windows ("Makefile:21: **\* multiple target patterns" error)

**Comment by josdeweger-zz** [comment]
I created a PR for this one: https://github.com/mzabriskie/react-draggable/pull/127

**Comment by STRML** [comment]
You can now adjust this in `2.x` by setting the element's `position.x` or `position.y` independently of whether or not `axis` is defined.
