### ISSUE TITLE
there is no way to set position after render

### ISSUE THREAD

**Issue by Kepro** [react-grid-layout/react-draggable#110]
Hi, is there any way how to set position after render? 
i have "windows" application and i have maximalize window then i need to change position to top, left for fullscreen or i need only do override with CSS?

```
.fullscreen {
      transform: translate(0,0) !important;
      width: 100% !important;
      height: 100% !important;
    }
```

**Comment by STRML** [comment]
Do so via CSS, change the `key` to create a new element, or use [DraggableCore](https://github.com/mzabriskie/react-draggable#draggablecore-api) if you need to control the element programmatically.

**Comment by Kepro** [comment]
thanks for very fast answer! ;)
