### ISSUE TITLE
server side rendering

### ISSUE THREAD

**Issue by Belsi** [react-grid-layout/react-draggable#112]
I used version 0.8.0 and i got warning

``` javascript
Warning: Draggable.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance) instead.
```

I have updated it to 1.0.0 which fixed this problem, but new one appears:

``` javascript
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) translate(10px,0px);-webkit-transform:tr
 (server) translate(10px,0px);" data-reactid=".1dp
```

I am using webpack postcss according to the recommendations

``` javascript
postcss: () => [autoprefixer({browsers: 'last 2 version'})],
```

but I still have this problem.
I think it is a bug, becouse the older version hasn't got this problem. Or am i doing something wrong?

**Comment by dtschust** [comment]
You're not doing something wrong. When react-draggable adds the translate style, it tries to also add the appropriate vendor prefix, seen here: https://github.com/mzabriskie/react-draggable/blob/f4de99c4353c58ef89c7fe836b25e43f947c64eb/lib/utils/domFns.es6#L85 . On the server render the browser is unknown so no vendor prefix is added, resulting in a difference between server and client markup. I'm seeing this same issue.

**Comment by STRML** [comment]
This is a good point.

I was trying to get clever and save some writing to the DOM but I think we just have to write all the prefixes to be sure that we're correct in all envs.
