### ISSUE TITLE
setting position using code

### ISSUE THREAD

**Issue by chrisdrackett** [react-grid-layout/react-draggable#113]
I'm trying to use this with a `Switch` component letting the user drag the switch to an on or off position. I've got then working with dragging only but want to also support the following cases:
- user clicks the element (switch swaps sides)
- user drags most of the way, but not all (animate the switch to the final position)

I've been looking over the tickets and it seems like I might need to do this using `top` and `left` potentially, which could end up being a pain. Maybe I'm missing something about `DraggableCore`?

**Comment by STRML** [comment]
This is easier now with `<Draggable position={{x: 0, y: 0}}>`.
