### ISSUE TITLE
A strange GET request to react-draggable.js.map

### ISSUE THREAD

**Issue by ripitrust** [react-grid-layout/react-draggable#115]
Hi 
I got a strange GET request to the react-draggable.js.map:

"GET /static/js/build/react-draggable.js.map HTTP/1.1" 404"

Not sure where this came from,  I am using webpack and a  npm require statement:

var Draggable = require('react-draggable')

I searched all the bundle file webpack generated but did not find this also

**Comment by STRML** [comment]
This is standard behavior for source maps - the builds include a sourcemap comment at the bottom. The request is only made if the devtools are open. You can strip them intentionally if you like with uglify.
