### ISSUE TITLE
Child input not focusing on touch events

### ISSUE THREAD

**Issue by dunckr** [react-grid-layout/react-draggable#116]
Thanks for making this library it has been really helpful for us.

We have found an issue with child input events not focusing on touch events. To reproduce:
- [Add an input element](https://github.com/dunckr/react-draggable/blob/gh-pages/example/index.html#L96) as child of `Draggable`

``` js
<Draggable zIndex={100} {...drags}>
   <input type="text" placeholder="I cannot be focused" />
</Draggable>
```
- Turn on mobile mode/spoof touch events
- Click on the input
- Input never receives focus

Example [here](http://dunckr.github.io/react-draggable/example/) on the _top right_

It is a problem with the [ghost click hack](https://github.com/mzabriskie/react-draggable/blob/master/lib/DraggableCore.es6#L391) on `onMouseDown`.  This prevents the event from propagating to the input. As this is to fix another issue I'm not too what is the best way to handle it.

We are overriding the `onMouseDown` function using the reference to `Draggable` in our `componentDidMount` and ignoring the ghost click hack.

Thanks

**Comment by xrado** [comment]
+1

**Comment by STRML** [comment]
Gave up on ghost click handling entirely - too many gotchas, too many weird mobile browsers.

**Comment by berkaytheunicorn** [comment]
Did you ever fixed the issue or found a workaround? @STRML

**Comment by STRML** [comment]
I believe we removed the ghost click handling. Is this still an issue for
you on the latest version?

**Comment by berkaytheunicorn** [comment]
not tested yet I will test and get back to you. ;) thanks

**Comment by adtm** [comment]
Has it been solved? Because I still encounter this problem with not selecting the `input`

**Comment by sag1v** [comment]
this is still an open issue, you can't focus inputs nested inside `Draggable` (not only on TouchEvents)

**Comment by dcorb** [comment]
Solved with the "cancel" prop?  https://github.com/mzabriskie/react-draggable/issues/314
