### ISSUE TITLE
Get Control Position on Mobile

### ISSUE THREAD

**Issue by ghost** [react-grid-layout/react-draggable#118]
Not really a major issue if you're just dragging elements and not recording the positions anywhere... but we were having trouble returning the position of a dragged element on mobile devices and traced it back to getControlPosition()

We fixed this by changing:
var position = e.targetTouches && e.targetTouches[0] || e;
to
var position = e.changedTouches && e.changedTouches[0] || e;

targetTouches was returning empty for us in iOS and Android.

**Comment by STRML** [comment]
Fixed in `2.0.2`.
