### ISSUE TITLE
Provide typescript definitions

### ISSUE THREAD

**Issue by Strate** [react-grid-layout/react-draggable#119]
Hi!

In readme file you provide description of props, written in typescript notation. Could you please provide `d.ts` file?

**Comment by STRML** [comment]
That's just habit from writing a lot of Flow code. Happy to accept a `d.ts` pull request, I don't use TypeScript personally.

**Comment by erfangc** [comment]
Here is what I came up with, please give me your opinions, before we make this a PR to either this Repo or the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo.

Something is definitely amiss, as the following only works if we ask TS to target ES6. Not sure what needs to be done to ensure more robust compatibility.

``` ts
///<reference path="typings/react/react.d.ts"/>

declare module 'react-draggable' {

    import {Component} from 'react';
    import Props = __React.Props;

    interface DraggableBounds {
        left: number
        right: number
        top: number
        bottom:number
    }

    interface DraggableProps extends Props<Draggable> {
        axis?: string
        bounds?: DraggableBounds|string|boolean
        start?:{x:number,y:number}
        zIndex?:number
    }

    interface DraggableCoreProps extends Props<DraggableCore> {
        allowAnyClick: boolean
        disabled: boolean
        enableUserSelectHack: boolean
        grid: number[]
        handle: string
        cancel: string
        onStart: (event, ui) => boolean
        onDrag: (event, ui) => boolean
        onStop: (event, ui) => boolean
        onMouseDown: (event, ui) => boolean
    }

    export default class Draggable extends Component<DraggableProps, any> {
    }

    export class DraggableCore extends Component<DraggableCoreProps, any> {
    }

}
```

``` json
{
    "compilerOptions": {
        "module": "es6",
        "target": "es6",
        "sourceMap": true,
        "jsx": "react"
    },
    "exclude": [
        "node_modules"
    ]
}
```

``` jsx
// sample code
///<reference path="react-draggable.d.ts"/>
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import {default as Draggable, DraggableProps} from 'react-draggable';
import * as ReactDraggable from 'react-draggable';

class SampleComponent extends React.Component<any,any> {
    constructor(props:any) {
        super(props);
    }

    render() {

        const props:DraggableProps = {};
        debugger;
        return (
            <Draggable {...props}>
                <div>
                    <h1>Hello World!</h1>
                </div>
            </Draggable>
        )
    }
}
ReactDOM.render(<SampleComponent/>, document.getElementById("content"));
```

**Comment by erfangc** [comment]
My first time writing ambient typescript files, @Strate let me know if there are any preferences ... 

I was thinking we could 
1. make component `.d.ts` files available through `tsd`, in that case we can explicitly depend on `react-global` and we will know the relative location of `react-global.d.ts` for our `/// <reference .../>` tag
2. bundle the `.d.ts` file with this package in `npm` (which Microsoft recommends as it enables versioning of the exported shapes). However, in that case, we won't be able to reference core react symbols without re-creating them

**Comment by STRML** [comment]
I haven't had much time to review this, and I use Flow, not TS personally,
so I'm rough on some of the defs. I do see what seems to be a double import
statement in the second block of code, the import *, perhaps that is
causing trouble.

**Comment by erfangc** [comment]
the imports actually do not affect runtime, as the `.d.ts` file is not emitted or loaded. the runtime problems seems to be again related to how `systemjs` treats `default` exports and how TypeScript convert import statements in different module formats ... gotta do a little more digging ... but that is a slightly separate issue than just writing the `.d.ts` file, so the file above should be roughly good unless @Strate has any specific suggestions.

**Comment by scniro** [comment]
+1

**Comment by emzinnia** [comment]
What's the status on this?

Does anything else need to be done?

**Comment by trevorhanus** [comment]
+1

**Comment by twop** [comment]
+1. Would love to use it but I use TypeScript :(

**Comment by STRML** [comment]
@everyone please consider contributing these definitions (it is not a large
or complex library) rather than filling my inbox with +1s.

**Comment by erfangc** [comment]
can we re-open ... I just added a PR

**Comment by jessewatson** [comment]
I see the typescript definitions up here on GitHub, but they are not coming down with "npm install react-draggable". Do I have to build locally to get them at this point?

**Comment by eldamir** [comment]
@jessewatson I tried simply doing `npm install --save git+https://github.com/mzabriskie/react-draggable` to just install master, but it seems that the typedefinitions are not correctly implemented, at least for my version of typescript (2.1.5)

@erfangc Any ideas?

```
ERROR in /***/node_modules/react-draggable/index.d.ts
(49,1): error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.

ERROR in /***/node_modules/react-draggable/index.d.ts
(49,7): error TS2323: Cannot redeclare exported variable 'Draggable'.

ERROR in /***/node_modules/react-draggable/index.d.ts
(49,66): error TS2304: Cannot find name 'DraggableState'.

ERROR in /***/node_modules/react-draggable/index.d.ts
(53,7): error TS2323: Cannot redeclare exported variable 'DraggableCore'.

ERROR in /***/node_modules/react-draggable/index.d.ts
(53,74): error TS2304: Cannot find name 'DraggableState'.

ERROR in /***/node_modules/react-draggable/index.d.ts
(58,3): error TS2666: Exports and export assignments are not permitted in module augmentations.

ERROR in /***/node_modules/react-draggable/index.d.ts
(59,5): error TS2323: Cannot redeclare exported variable 'Draggable'.

ERROR in /***/node_modules/react-draggable/index.d.ts
(59,5): error TS2484: Export declaration conflicts with exported declaration of 'Draggable'

ERROR in /***/node_modules/react-draggable/index.d.ts
(60,5): error TS2323: Cannot redeclare exported variable 'DraggableCore'.

ERROR in /***/node_modules/react-draggable/index.d.ts
(60,5): error TS2484: Export declaration conflicts with exported declaration of 'DraggableCore'

ERROR in ./src/components/dialog.tsx
(4,9): error TS2305: Module '"/***/node_modules/react-draggable/index"' has no export
```
