### ISSUE TITLE
How to create snapable drag items

### ISSUE THREAD

**Issue by julienvincent** [react-grid-layout/react-draggable#120]
Can someone show me a simple example of how to create a draggable component that snaps to a position on dragEnd?

**Comment by STRML** [comment]
This is not a support forum, this is for bugs.

**Comment by capsudo** [comment]
This is what I do (im my case I only allow dragging along x axis):

```jsx
const [snapPosition, setSnapPosition] = useState(0);
const snapWidth = 100;
const onStop = (event, { x }) => {
	const closestPosition = Math.round(x / snapWidth) * snapWidth; // find closest position on "grid"
	setSnapPosition(closestPosition ); // update state
};
return <Draggable axis="x" position={{ x: snapPosition, y: 0 }}onStop={onStop}>...</Draggable>;
```

to snap back to closest "point" on left or right only use `Math.floor`/`Math.ceil` instead of `Math.round`
