### ISSUE TITLE
How to use with react-resizable

### ISSUE THREAD

**Issue by geohuz** [react-grid-layout/react-draggable#121]
I'm having problem of using the two together, The component always response to drag event, the resize can't be started. Any suggestion on this issue?

**Comment by zacklitzsinger** [comment]
You probably need to add `cancel={".react-resizable-handle"}` on Draggable like react-grid-layout does.

**Comment by Ajamuar** [comment]
This is not fixing the issue. When trying to resize, the entire div moves instead of resizing.

You can see a working example here: https://codesandbox.io/s/fervent-cerf-0z335q?file=/src/components/Line.tsx
