### ISSUE TITLE
unmount during drag causes invariant throw

### ISSUE THREAD

**Issue by AndrewRayCode** [react-grid-layout/react-draggable#130]
`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Draggable component.`

**Comment by STRML** [comment]
Should be as simple as setting `dragging: false` in CWUM so the drag/dragStop handlers stop firing.

**Comment by kis** [comment]
I have the same issue

**Comment by drorsun** [comment]
not 100% sure if related - after removing an item from a draggle grid, I get this - 
`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.warning`

**Comment by STRML** [comment]
This was just fixed in https://github.com/mzabriskie/react-draggable/commit/f11b37da270a90adadb05f1d12748a3f17bbf809 and released as `v1.2.0`.
