### ISSUE TITLE
Handling other mouse events inside handle

### ISSUE THREAD

**Issue by jolyonruss** [react-grid-layout/react-draggable#136]
Hi Matt,

Firstly thanks for react-draggable, I've been using it for a couple of weeks building a sortable list and it's made my life a lot easier.

At the moment I'm using DraggableCore and translating my elements myself - each of my draggable elements have additional UI controls inside them. I can attach click handlers to those UI controls, but I'd like to be able to drag through them as well. So my JSX looks like this:

```
<DraggableCore
    ref={'draggable'}
    handle=".project-handle"
    onStart={ this.props.onDragStartCallback }
    onDrag={ this.props.onDragCallback }
    onStop={ this.props.onDragStopCallback }
    key={ this.props.image.id }
    >
    <div className={ 'project-handle' }>
        <div onClick={ this.handleClick }>amazing button - </div>
    </div>
</DraggableCore>
```

I uploaded a video to show you what I mean - https://vid.me/nefV

I want to be able to drag the component when I click and hold in the amazing button.

I appreciate this might be a niche problem, so not something you would want to put into the main lib, but I'd happily fork and patch, if you could point me in the right direction to solve this problem.

Cheers, Jolyon

**Comment by STRML** [comment]
The problem is probably because you are canceling the event in `handleClick`. Any part of the element will be draggable if you omit `handle`. Setting the handle selector to match the root container is the same as omitting it.

Without further code I can't help you, but this is really not proper for an Issue, but rather for IRC.
