### ISSUE TITLE
Avoid selecting text in drag handler when attempting a drag

### ISSUE THREAD

**Issue by nataliethistime** [react-grid-layout/react-draggable#137]
I have text inside my drag handler element (it's the title bar in a modal dialog developed). Sometimes dragging from the handler highlights the text rather than moving it. Is there a way to avoid this?

**Comment by cmmcleod** [comment]
Use CSS `user-select: none`

https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

The may want to add/remove the CSS (either through classes or styles) depending on the behavior you want. Any elements that are [always] draggable should probably have this CSS applied

**Comment by nataliethistime** [comment]
Thanks @cmmcleod that was half the solution.

I also had to wrap the text in a span and give it the class I was using as the Draggable's drag handle.

**Comment by dkozar** [comment]
If I might suggest, the drag handle(s) should be an array of items - not only it would solve this problem, but would allow multiple handles for a single draggable on different positions (not a rare case).

Danko
