### ISSUE TITLE
No way to account for drag values on scaled elements

### ISSUE THREAD

**Issue by davidturissini** [react-grid-layout/react-draggable#139]
There doesn't appear to be any way to modify drag values for an element that is scaled. In this situation, you would want the element to continue to track the mouse as it would with `scale(1)`, but because it is scaled it lags behind.

For instance, if you dragged an element with `scale(0.5)` 10 pixels, it would have moved 10 pixels, but with the 0.5 scale applied it would appear to the user to only have moved 5 pixels.

I think exposing a new `scale` or `zoom` property or new callbacl would be useful to modify the drag values before they are applied.

**Comment by kamui** [comment]
I'm also looking for a way to do this. I'm trying to implement a zoom feature with transform scale and using draggable to handle the panning, but the dragging is multiplied by the scale value, so for each pixel you translate, it's multiplied by the scale factor.

**Comment by STRML** [comment]
You could do this in 2.0 beta using position, or using DraggableCore.
Simply watch the deltas and move the item yourself by multiplying the
deltas by the scale.

**Comment by RonnieCui** [comment]
I`m using "react-draggable": "^2.2.1", DraggableCore don`t help me , Could you tell me how to use the method of position?

**Comment by ecoukraine** [comment]
Hi guys,

would you be kind to share the solution here? It's still unclear how to support dynamically changeable scale value.

Thank you
