### ISSUE TITLE
How to push other elements aside

### ISSUE THREAD

**Issue by Waize** [react-grid-layout/react-draggable#142]
Hello,

I hope you can help me with my issue. 
I have a normal list of elements:

```
<select size={size}>
<option>foo</option>
<option>bar</option>
<option>muh</option>
</select>
```

It is no problem to drag an dropping each single option. But I want to drag "muh", put it as the first item and push "foo" and "bar" aside, so that the order will be "muh, foo, bar". 
Is this possible to do? 

Thanks, 
Paul

**Comment by STRML** [comment]
That's more advanced usage and outside the scope of this module. You could accomplish it by using `<DraggableCore>` and watching for overlap, then moving elements when they do.

I have built [react-grid-layout](https://github.com/STRML/react-grid-layout) which may do what you need. [React-DnD](https://github.com/gaearon/react-dnd) may as well.
