### ISSUE TITLE
Dragging element externally (programatically).

### ISSUE THREAD

**Issue by HarshaVardhanPVK** [react-grid-layout/react-draggable#143]
I am dragging the component externally (programatically) by using id selector.

document.getElementById("draggable").style.transform = "translate(100px, 0px)";

This is working fine but when I am dragging it from the current position with the help of mouse it is accessed from previous position where it is placed by mouse but not from the position where I dragged it programatically.

By this some inconsistency is taking place. Please help me to overcome this.
Or any other way to drag component externally?

Thanks in advance.

**Comment by STRML** [comment]
That's not how React works - you need to set props on the container. Use the `position` prop or `<DraggableCore>`.
