### ISSUE TITLE
start prop doesnt work

### ISSUE THREAD

**Issue by pizzarob** [react-grid-layout/react-draggable#146]
passing in an object with x and y key value pairs does not move the draggable box

**Comment by mosvov** [comment]
I have same bug:
 start={{x: this.state.element_start, y: 0}}

**Comment by mosvov** [comment]
I found solution:
 this.refs.draggable_element.setState({clientX:this.state.element_start});

**Comment by STRML** [comment]
`2.x` now has a `position` prop.
