### ISSUE TITLE
onDrag position outside bounds

### ISSUE THREAD

**Issue by ghost** [react-grid-layout/react-draggable#147]
I'm having problem reading correct onDrag position.left/top outside bounds. It appears when outside bounds and re-entering.
I've tried to compensate using this.refs.myDraggable.state.slackX / Y but still got random jitter occasionally. I get the exact values using this.refs.myDraggable.state.clientX / Y but that results in a delay when setting state onDrag. 
Is there another way to do this?
Thanks!

**Comment by STRML** [comment]
Are you still having this issue? I patched some issues in `slackX/Y` in 2.x. If not, please provide a failing example.
