### ISSUE TITLE
Support for dragTarget? **BUG**

### ISSUE THREAD

**Issue by ivansglazunov** [react-grid-layout/react-draggable#160]

**Comment by STRML** [comment]
This is not a support forum, this is for bugs in `<Draggable>`. Take it to IRC

**Comment by ivansglazunov** [comment]
I'm sorry for new issue in your clean "only bugs issues". #13 
You do not plan to even a hint of how to use this package for the handle drop target?
I believe the lack of this feature, it is a bug.
And ... you are wrong , it is support forum, and anything, until it is open repository, and there are people. And you can use label `bug`...
👎 
IRS channel of package or yours I have not found.
You could say that it was not built, and maybe it would have changed by now.

**Comment by STRML** [comment]
Free software is just that, free. Nobody owes you anything. You are welcome to submit a pull request.

**Comment by ivansglazunov** [comment]
I'll be glad to make a pull request,but first, I'd prefer to talk about this with contributors. If not here, I would like to know where.
I want to know why it's not? Is there any reason?
Is there a desire to see it, and in what form?
Some additional tool (any links) is now resolved this problem?

---

Yes. Nobody owes me anything. However, we (contributors and motivated developers) owe this package.

---

Thank you for your understanding and patience.

**Comment by ivansglazunov** [comment]
What if?:
- Handle `onDragStop` event and save in the context `dropped` variable.
- Handle `onMouseOver` event, if context `dropped` exists, get it and clear valiable in context.
- Run `onDrop` event in `onMouseOver` emitter.

This is because onDrop not thrown in this case.

**Comment by ivansglazunov** [comment]
Its works for me.

``` jsx
import React from 'react';

import { DraggableCore } from 'react-draggable';

class Context extends React.Component {
  constructor(...args) {
    super(...args);
    this.state = {
      drag: null,
      event: null,
      dropped: null
    }
  }
  getChildContext() {
    return {
      setDrag: (...args) => this.setDrag(...args),
      setDropped: (...args) => this.setDropped(...args),
      unsetDropped: () => this.unsetDropped(),
      dropped: this.state.dropped
    };
  }
  setDrag(drag, position) {
    this.setState({
      drag, position
    });
  }
  setDropped(drag) {
    this.setState({
      dropped: drag
    });
  }
  unsetDropped() {
    this.setState({
      dropped: null
    });
  }
  onMouseMove() {
    this.unsetDropped();
  }
  render() {
    return (
      <span onMouseMove={!this.state.drag&&this.state.dropped?((...args) => this.onMouseMove(...args)):null}>
        {this.props.children}
        {this.state.position&&this.state.drag?
          <div style={{
            zIndex: 999999,
            position: 'absolute',
            left: this.state.position.left, top: this.state.position.top
          }}>
            {this.state.drag.props.component}
          </div>
        :null}
      </span>
    );
  }
}

Context.childContextTypes = {
  setDrag: React.PropTypes.any,
  setDropped: React.PropTypes.any,
  unsetDropped: React.PropTypes.any,
  dropped: React.PropTypes.any
};

class Drag extends React.Component {
  constructor(...args) {
    super(...args);
    this.state = {
      draggable: false
    };
  }
  onDrag(event, coreData) {
    this.setState({
      draggable: true
    });
    this.context.setDrag(this, { left: event.clientX, top: event.clientY });
  }
  onDragStop(event, coreData) {
    this.setState({
      draggable: false
    });
    this.context.setDropped(this);
    this.context.setDrag();
  }
  render() {
    return (
      <DraggableCore
        ref="draggable"
        onDrag={(...args) => this.onDrag(...args)}
        onStop={(...args) => this.onDragStop(...args)}
      >
        {React.cloneElement(React.Children.only(this.props.children), {
          disabled: this.state.draggable
        })}
      </DraggableCore>
    );
  }
}

Drag.contextTypes = {
  setDrag: React.PropTypes.any,
  setDropped: React.PropTypes.any,
  unsetDropped: React.PropTypes.any
};

class Drop extends React.Component {
  onMouseMove(event) {
    var dropped = this.context.dropped;
    this.context.unsetDropped()
    this.onDrop(event, dropped);
  }
  onDrop(event, dropped) {
    if (this.props.onDrop) {
      this.props.onDrop(event, dropped);
    }
  }
  render() {
    return React.cloneElement(React.Children.only(this.props.children), {
      onMouseMove: this.context.dropped?(...args) => this.onMouseMove(...args):null
    });
  }
}

Drop.contextTypes = {
  dropped: React.PropTypes.any,
  unsetDropped: React.PropTypes.any
};

export { Context, Drag, Drop };
```

Some people would like to see it within the `react-draggable` package? Or make a separate package? I am not against the process demo and documentation based on jsdoc.

> In this example, i do not use `<Draggable/>`, but use `<DraggableCore/>`. However, nothing prevents you to make use of it..

**Comment by ivansglazunov** [comment]
If `drag` is a small element, `onMouseOver` is triggered earlier than `dropped`, `onMouseMove` is better.

**Comment by ivansglazunov** [comment]
It is if you do not use not cross-browser [pointer-events: 'none'](https://developer.mozilla.org/ru/docs/Web/CSS/pointer-events)
