### ISSUE TITLE
Uncaught TypeError: Cannot read property 'SVGElement' of undefined

### ISSUE THREAD

**Issue by tlrobinson** [react-grid-layout/react-draggable#162]
In v2.1.1 I'm getting this error when trying to use `Draggable`:

`react-draggable.js:267 Uncaught TypeError: Cannot read property 'SVGElement' of undefined`

It looks like the problem has to do with `global` being `undefined` due to `(function() { return this; })()` returning `null` rather than the global object in strict mode. I'm not really sure why it's being executed in strict mode though.

**Comment by STRML** [comment]
That's odd. Strict mode is intended and implied in Babel modules, but Webpack should be handling global injection properly.

I don't see this issue on any of the demos. Perhaps it has something to do with your environment?

**Comment by artemstorozhuk** [comment]
Exactly same issue for me. I've got no idea how to fix it.

**Comment by STRML** [comment]
You could help by giving me reproduction steps.

**Comment by artemstorozhuk** [comment]
Thanks for your quick response.

In console:
`npm i --save react-draggable`

In code:

```
import React from 'react'
import {render} from 'react-dom'
import Draggable from 'react-draggable';

render(
    <Draggable>
        <div>content</div>
    </Draggable>,
    document.getElementById('root')
);

```

Btw component is dragging properly.

**Comment by amoilanen** [comment]
Might be that I found a workaround.

Observed the same error when the code of `react-draggable` was run through the Babel transform by Webpack while being located under 'node_modules'. After turning off the Babel transform the issue disappeared, now no errors in the console.

Looks like some Webpack + Babel issue.
