### ISSUE TITLE
Safari for ipad drag drop not working

### ISSUE THREAD

**Issue by JaneCoder** [react-grid-layout/react-draggable#165]
The touch interface worked great in laptops and on iPhone. But on iPad there are issues. In the demo page, vertically dragging most elements drags the whole screen, causing scrolling rather than drag of the element. 

Elements inside the 'parent' box do drag both vertically and horizontally, but if they drag over each other they begin to drag in tandem as if connected to one another.

**Comment by JaneCoder** [comment]
I think the answer may be to stop the device scroll when touch is dragging the draggables. Will work on getting that to work today.  I had some small success with this idea so far.

**Comment by JaneCoder** [comment]
So I was able to monkey patch the js created by webpack for me to fix this issue in iPad.

I added a function and a boolean to stop scrolling and keep up with it if was stopped:

```
_this.removeScroll` = function(e) {e.preventDefault(); return false},
_this.scrolling = true,  // TODO: should be state.
```

set the function on the document as an event listener in the handleDrag function:

```
if(_this.scrolling == true && _this.state.dragging) {
    document.addEventListener('touchmove', _this.removeScroll)
    _this.scrolling = false;
}
```

and removed the event onTouchEnd

`document.removeEventListener('touchmove', _this.removeScroll, false);`

I had challenges getting it to work with handleDragStart and stop. Now I just need to lean es6 and karma.

**Comment by amangeot** [comment]
Hi @JaneCoder, did you find a way to fix it that could be integrated here with a pull request ?

**Comment by amangeot** [comment]
Wow, great,no apologize needed, thank you a lot for your work !

I have a slightly unrelated question. Let's say we have a `<Draggable axis='x' />`, is it technically possible to only drag the `Draggable` on horizontal dragging, and let the entire page scroll on vertical dragging ?

Take good care of you,

**Comment by STRML** [comment]
This was fixed in 2.2.3. Thanks for the contribution.

**Comment by JaneCoder** [comment]
Hello, can you tell me if there are plans soon to import this version into react-grid-layout?
Thanks!

**Comment by STRML** [comment]
@JaneCoder RGL should already get this version, all you need to do is update your dependencies.

**Comment by JaneCoder** [comment]
When I checked package.json on github I thought RGL was on draggable v 2.1.1
Maybe I was looking at the wrong thing. Thanks!

**Comment by JaneCoder** [comment]
Is there some special branch I need to get so that I have v.2.2.3 of
react-draggable included?

**Comment by STRML** [comment]
RGL depends on `^2.1.1`, which is all semver-minor versions above and including 2.1.1. You just need to do a deep upgrade. If you're using a shrinkwrap file you'll have to update it in there. Easiest way is probably to `npm rm react-grid-layout; npm install react-grid-layout`
