### ISSUE TITLE
DraggableCore: throttle drag events

### ISSUE THREAD

**Issue by ajrouvoet** [react-grid-layout/react-draggable#172]
For performance heavy eventhandlers it's often necessary to throttle drag events before handling them.
Currently this is made difficult due to the fact that if one throttles the dragHandler, one simply misses events; i.e. deltas are not grouped together easily.

Is this something that DraggableCore could support?

One idea would be to add a property that sets a time-window and emit only one event for the set of underlying drag events that happened in that window. Deltas should be summed within the window.

**Comment by STRML** [comment]
Why not throttle the expensive part of your handler? I'd like to keep that
kind of complexity out of this module.

**Comment by ajrouvoet** [comment]
Yeah that's definitly possible. It's just that there is a large "common" part in throttling drag-events and only a very small usage-part. So conceptually it made sense to me to have it as part of react-draggable for reuse. 

It doesn't need to be part of DraggableCore of course. It could be a component that composes DraggableCore.

**Comment by STRML** [comment]
Technically you could also use `<Draggable>`, set the `axis` to `'none'` to prevent moving while dragging and set the `position` property yourself. Then just listen to drag events. `<Draggable>` will keep track of its own position.

Depending on what you're doing that may be more or less complicated than writing your own HOC.

**Comment by ajrouvoet** [comment]
Interesting approach. I assume Draggable doesn't add much unnecessary overhead to the handler?

**Comment by STRML** [comment]
Not really. The main difference is that it manages CSS translations itself (which you can turn off with `axis`) and it manages its own state, which is mandatory if you want it to tell you how much it's moved in absolute terms, no matter how many drag messages you ignore.

**Comment by dkozar** [comment]
From my own experience, when dragging elements on screen, deltas are something you don't want to rely on. You should only rely on "absolute" delta, which implies that draggable should save the starting point from where the drag started. A difference between the current point and the starting one gives you the absolute delta (draggable could also provide a helper method for it).

This absolute delta is immune to throttling.

Danko

**Comment by STRML** [comment]
Yes, which involves state. `<DraggableCore>` is stateless. `<Draggable>`
is not. That's why there are two components.

**Comment by dkozar** [comment]
I would say not necessary the _React_ state (used to trigger render), but non-state non-props DOM- related "state" (simple Javascript variable holding the coordinate of drag start).

But yeah, people for some reason avoid to use simple JS outside of React state.

Danko

**Comment by STRML** [comment]
It is intentional as it has previously been very painful to manage
overriding state in these components. I have built several large projects
on top of Draggable and thus I built something simple and stateless. It's
purpose is only to abstract away browser difficulties. It is a building
block.

If you need more, build a hoc.
