### ISSUE TITLE
Uncaught Invariant Violation: getNodeFromInstance: Invalid argument.

### ISSUE THREAD

**Issue by L3V147H4N** [react-grid-layout/react-draggable#181]
Using:

```
"react": "^15.0.2",
"react-addons-css-transition-group": "^15.2.1",
"react-addons-shallow-compare": "^15.2.1",
"react-dom": "^15.0.2",
"react-draggable": "^2.1.2",
```

Code:

```
<Draggable>
  ...
</Draggable>
```

Error occurs when trying to drag

Full Error:

`Uncaught Invariant Violation: getNodeFromInstance: Invalid argument.invariant @ D:\SistarJsDesktopTemp\node_modules\fbjs\lib\invariant.js:38getNodeFromInstance @ D:\SistarJsDesktopTemp\node_modules\react\lib\ReactDOMComponentTree.js:156findDOMNode @ D:\SistarJsDesktopTemp\node_modules\react\lib\findDOMNode.js:50getControlPosition @ D:\SistarJsDesktopTemp\node_modules\react-draggable\dist\react-draggable.js:903DraggableCore._this.handleDragStart @ D:\SistarJsDesktopTemp\node_modules\react-draggable\dist\react-draggable.js:1064DraggableCore._this.onMouseDown @ D:\SistarJsDesktopTemp\node_modules\react-draggable\dist\react-draggable.js:1183ReactErrorUtils.invokeGuardedCallback @ D:\SistarJsDesktopTemp\app\node_modules\react\lib\ReactErrorUtils.js:70executeDispatch @ D:\SistarJsDesktopTemp\app\node_modules\react\lib\EventPluginUtils.js:87executeDispatchesInOrder @ D:\SistarJsDesktopTemp\app\node_modules\react\lib\EventPluginUtils.js:110executeDispatchesAndRelease @ D:\SistarJsDesktopTemp\app\node_modules\react\lib\EventPluginHub.js:42executeDispatchesAndReleaseTopLevel @ D:\SistarJsDesktopTemp\app\node_modules\react\lib\EventPluginHub.js:53forEachAccumulated @ D:\SistarJsDesktopTemp\app\node_modules\react\lib\forEachAccumulated.js:24processEventQueue @ D:\SistarJsDesktopTemp\app\node_modules\react\lib\EventPluginHub.js:215runEventQueueInBatch @ D:\SistarJsDesktopTemp\app\node_modules\react\lib\ReactEventEmitterMixin.js:18handleTopLevel @ D:\SistarJsDesktopTemp\app\node_modules\react\lib\ReactEventEmitterMixin.js:29handleTopLevelImpl @ D:\SistarJsDesktopTemp\app\node_modules\react\lib\ReactEventListener.js:73perform @ D:\SistarJsDesktopTemp\app\node_modules\react\lib\Transaction.js:136batchedUpdates @ D:\SistarJsDesktopTemp\app\node_modules\react\lib\ReactDefaultBatchingStrategy.js:63batchedUpdates @ D:\SistarJsDesktopTemp\app\node_modules\react\lib\ReactUpdates.js:98dispatchEvent @`

**Comment by L3V147H4N** [comment]
On the subject, https://github.com/furqanZafar/react-selectize causes the same error, could be a react thing?

**Comment by STRML** [comment]
I can't reproduce this. If you could create a demonstrating jsfiddle or webpackbin that would be helpful. Please reopen if you do.
