### ISSUE TITLE
Run tests in Windows at AppVeyor

### ISSUE THREAD

**Issue by paazmaya** [react-grid-layout/react-draggable#192]
http://www.appveyor.com/ runs on Windows and could be used to run Karma against Internet Explorer 11.

How about it?

http://www.appveyor.com/docs/installed-software#selenium

**Comment by STRML** [comment]
Sure, would be happy to accept a PR if you can get it working.

**Comment by paazmaya** [comment]
Available via #194

**Comment by paazmaya** [comment]
@STRML the PR is available at #194 and once the AppVeyor has been enabled for this project, then we can see if it was success or not.

**Comment by STRML** [comment]
@mzabriskie Could you please enable AppVeyor?

**Comment by STRML** [comment]
AppVeyor is enabled.
