### ISSUE TITLE
DraggableCore still set transform?

### ISSUE THREAD

**Issue by TranquilMarmot** [react-grid-layout/react-draggable#195]
It's stated in the readme that `DraggableCore` "does not set styles or transforms on itself and thus must have callbacks attached to be useful" but even using `DraggableCore` the `trasnform` of the element inside of it is being set.

i.e...

``` jsx
<DraggableCore>
   <div>Hello</div>
</DraggableCore>
```

I can still drag the div around and it has i.e. `style="transform(222px, 79px)"` applied to it.

Am I missing a setting somewhere, or is the readme just misleading/incorrect? I only want to get the callbacks called, not have any styles set.

**Comment by STRML** [comment]
Are you sure you're importing the correct component?

**Comment by TranquilMarmot** [comment]
Ah, I did have
`import DraggableCore from 'react-draggable';`

but the proper import is

`import { DraggableCore } from 'react-draggable';`
