### ISSUE TITLE
Rotate image

### ISSUE THREAD

**Issue by DanFlavius** [react-grid-layout/react-draggable#196]
Hello,

I would like to have a rotation on the draggable component, but, so far I can't find a way to do this in a easy way. What I do it was to add rotate css property in the createCSSTransform function, but I think this is not a solution. This is the code modified : `  function createCSSTransform(_ref) /_: Object_/ {
      var x = _ref.x;
      var y = _ref.y;

```
  // Replace unitless items with px
  return _defineProperty({}, (0, _getPrefix.browserPrefixToKey)('transform', _getPrefix2.default), 'rotate(' + x/50 +  'deg) translate(' + x + 'px,' + y + 'px)');
}`
```

It can be done in another way or you could add this feature? 
Please let me know and sorry if is not clear enough.

Regards!

**Comment by STRML** [comment]
If you want to rotate, you should likely wrap in another component to apply that transform. `<Draggable>` can't and won't parse the existing `transform` property to add its styles.

See the note in the third paragraph of https://github.com/mzabriskie/react-draggable#draggable.
