### ISSUE TITLE
Can't maintain item/element CSS transform properties. 

### ISSUE THREAD

**Issue by oshalygin** [react-grid-layout/react-draggable#197]
A little confused on the documentation of how to allow the item/element to maintain its own subset of transform CSS or even apply it dynamically.  Here is what the note rotation css looks like:

```
note: {
...someOtherProperties,
rotation:  {
                    transform: "rotate(18deg)"
                }
}
```

```
<Draggable>
            <div className="note"
                     style={note.rotation}>
                <p>{note.text}</p>
                <span>
                    <button onClick={() => onEdit(note.id) }
                        className="btn btn-primary glyphicon glyphicon-pencil"/>
                    <button onClick={onRemove}
                        className="btn btn-danger glyphicon glyphicon-trash"/>
                </span>
            </div>
</Draggable>
```

After reading this: 
_If the item you are dragging already has a CSS Transform applied, it will be overwritten by <Draggable>. Use an intermediate wrapper `(<Draggable><span>...</span></Draggable>)`in this case._ 

I tried doing the following but no dice.  I got my rotation to show up but I could no longer drag the element:

```
<Draggable>
<span>
            <div className="note"
                     style={note.rotation}>
                <p>{note.text}</p>
                <span>
                    <button onClick={() => onEdit(note.id) }
                        className="btn btn-primary glyphicon glyphicon-pencil"/>
                    <button onClick={onRemove}
                        className="btn btn-danger glyphicon glyphicon-trash"/>
                </span>
            </div>
</span>
</Draggable>
```

I tried using DraggableCore but that seemed like re-inventing the wheel with the library.

Any thoughts?

**Comment by oshalygin** [comment]
I actually solved it by nesting a div with another class component.  Please close

**Comment by cdaein** [comment]
@oshalygin I am also having the same issue where I can rotate but can't drag. Would you mind sharing some thoughts on this?
