### ISSUE TITLE
not work in React 0.13.3

### ISSUE THREAD

**Issue by pengxueshan** [react-grid-layout/react-draggable#202]
React: 0.13.3
Webpack: 1.13.1

Error: ./~/react-draggable/dist/react-draggable.js
Module not found: Error: Cannot resolve module 'react-dom'

**Comment by dmkelly** [comment]
It's working for me - this project doesn't list react-dom as a peer dependency, but you need to install it in your app `npm install react-dom@0.13.3 --save`

**Comment by STRML** [comment]
This does not support such an old version of React. You may be able to get
it working if you go through the old releases.
