### ISSUE TITLE
Question: is there any equivalent to jquery's containment api. Drag image in containers.

### ISSUE THREAD

**Issue by Kielan** [react-grid-layout/react-draggable#206]
I am looking to create a facebook cover upload feature. I want to contain the cover image within the div, filling by width but draggable vertically. I am new to this component and can't seem to find what I'm looking for. Can I solve this with react-draggable?

**Comment by STRML** [comment]
Yes, make the child the width of its container and set the bounds to `'parent'`, or otherwise use `<DraggableCore>` for fully custom behavior and only allow it to drag vertically.
