### ISSUE TITLE
Usage with unpkg.com

### ISSUE THREAD

**Issue by techniq** [react-grid-layout/react-draggable#208]
Initially I tried experimenting with `react-draggable` on  [Codepen](http://codepen.io/techniq/pen/GNGMYP?editors=0010) using `https://unpkg.com/react-draggable@2.2.3/dist/react-draggable.js` but I couldn't get the `onDrag` handler to fire.

I then fired up a quick create-react-app and copy/pasted the code (and put some of the components into their own files) and all works as expected.

When I console.log `DraggableCore` on both Codepen and my local app they both appear to be referencing the same code, so I'm a little stumped why it's not working on Codepen using unpkg.com.

## Codepen version
![screen shot 2016-12-08 at 10 15 13 am](https://cloud.githubusercontent.com/assets/177476/21015288/6efa7164-bd2f-11e6-9d25-54f33e7d3112.png)

## create-react-app version
![screen shot 2016-12-08 at 10 14 53 am](https://cloud.githubusercontent.com/assets/177476/21015280/67e089f4-bd2f-11e6-8154-f76b54bf4dfd.png)

Any ideas?

**Comment by STRML** [comment]
This has nothing to do with CodePen, it appears [this line](https://github.com/mzabriskie/react-draggable/blob/8a51de911fccb282d8444641dbd1e7b6d92ae603/lib/DraggableCore.es6#L206) is short-circuiting it.

I can't recall why I added that check, but it should be `Element`, not `Node`, to catch SVG.

**Comment by techniq** [comment]
Hmm, it works locally though (same 2.2.3 release).

Here's my local (create-react-app) code:

## App.js
```js
import React, { Component } from 'react';
import styled from 'styled-components';
import Node from './Node';

const Svg = styled.svg`
  border: 1px solid #ddd;
  width: 100%;
  height: 400px;
`;

class App extends Component {
  render() {
    return (
      <Svg>
        <Node x={20} y={20} />
        <Node x={60} y={60} />
        <Node x={100} y={100} />
        <Node x={140} y={140} />
      </Svg>
    );
  }
}

export default App;
```

## Node.js
```js
import React, { Component } from 'react';
import { DraggableCore } from 'react-draggable';

class Node extends Component {
  state = {
    x: this.props.x,
    y: this.props.y
  };

  handleDrag = (e, { deltaX, deltaY }) => {
    // console.log('drag', e, data);
    this.setState({
      x: this.state.x + deltaX,
      y: this.state.y + deltaY
    });
  };

  render() {
    const { x, y } = this.state;
    return (
      <DraggableCore onDrag={this.handleDrag}>
        <circle
          r="20"
          cx={x}
          cy={y}
        />
      </DraggableCore>
    )
  }
}

export default Node
```

**Comment by STRML** [comment]
Okay, so I found the issue:

In CodePen, the current code is executed in the global scope, not in a closure as it probably should be.

When you define `class Node extends Component`, you are overwriting `window.Node`, which is used in an `instanceof` check to ensure we're actually dragging an HTML Node.

That's why it works elsewhere. Rename that class [to anything else](http://codepen.io/anon/pen/zoaWZR?editors=0010) and it works.

**Comment by techniq** [comment]
Doh!  Good catch.  Renamed `Node` to `Item` and working on Codepen now.  Thanks for looking into it.

**Comment by STRML** [comment]
Yeah, honestly that's pretty odd that you can overwrite globals accidentally. Sent a tweet to Chris Coyier about it.

**Comment by techniq** [comment]
👍
