### ISSUE TITLE
Duplicated draggable element

### ISSUE THREAD

**Issue by cparadeise** [react-grid-layout/react-draggable#212]
http://screencast.com/t/aZq1x749a

I was playing around with the demo example in the source code. The draggable container with the 2 programmatic handlers attached to it was duplicated at some point, it may have happened when I dragged it off the initial page width. Another symptom that came from this is the ever increasing number of "Active Handlers" on the page. It was increasing when I kept dragging the problem container.

By the way this is one of the more superior libraries I've used that adds dragging capability seemlessly, thanks for the great work!

**Comment by STRML** [comment]
Hi - sorry, in order to fix this I'm going to need something else; or at least an animated gif and some steps, this computer does not run Flash.
