### ISSUE TITLE
"Easy" way to reset the applied drag?

### ISSUE THREAD

**Issue by Syndesi** [react-grid-layout/react-draggable#214]
Hi,

at first I want to thank you for this great component, it works really well in my application :D 
But in some cases I would like to rerender the parent with the Draggable-component, which should reset it's drag-position. But this is not the case. So could you please give me a hint how I could achieve it?
```javascript
<Parent>           // this should rerender itself
  <Draggable>      // this should reset it's drag-position
    <container />  // dragged container
  </Draggable>
</Parent>
```

Have a nice day, Syndesi

**Comment by STRML** [comment]
To completely reset the `<Draggable>`'s internal state, change its `key`. Otherwise, if you need greater control, use `<DraggableCore>`.

**Comment by tobi2424** [comment]
Hey. I've been struggling with the same issue and apparently you can set `position` to null on `Draggable` component when you start dragging (`onStart`) and then set it again to `{x: 0, y: 0}` when drag is stopped (`onStop`). It will reset position to it's origin.
