### ISSUE TITLE
Revert position when drag stops.

### ISSUE THREAD

**Issue by lukes** [react-grid-layout/react-draggable#220]
Hi, 

Thanks for maintaining this library!

Is there a way to have the `transform` revert back to 0,0 when the drag is over?

```javascript
<Draggable revert={boolean} />

<Draggable revert={this.shouldRevert.bind(someData)} />
```

Luke

**Comment by STRML** [comment]
Use `<DraggableCore>` and apply your own rules to move the element.

**Comment by lukes** [comment]
Thanks for your lightening quick response. 

I'm not sure if I'm mis-using this property, but I seem to achieved the exact behaviour I want using `<Draggable>`, by passing it `position={{x: 0, y: 0}}`. 

You can close this ticket if you like.
