### ISSUE TITLE
style ;user-select: none; not removed after removeUserSelectStyles

### ISSUE THREAD

**Issue by hemnstill** [react-grid-layout/react-draggable#222]
addUserSelectStyles may be called twice.
removeUserSelectStyles removes only one entry.

How to reproduce: Chrome. Try to drag something when is selected text. 
After resize is stopped ";user-select: none;" still exists in body.style.

Simple fix (DraggableCore.es6): 
if (style.indexOf(userSelectStyle) === -1)
  body.setAttribute('style', style + userSelectStyle);

**Comment by STRML** [comment]
Thanks. I really dislike this hack anyhow and would really rather add a className, but that gets tricky.

Could you submit a PR?

**Comment by STRML** [comment]
Never mind; just added it in latest commit; thanks for the report. Will be in the next release.

**Comment by hemnstill** [comment]
You fix will not work in IE, due to missing leading ;
Notable that this bug does not affected in IE :)

I suggest this method:

```
const userSelectStyle = `${userSelect}: none`;
...
  if (style.indexOf(userSelectStyle) === -1)
    body.setAttribute('style', `${style};${userSelectStyle};`);
}
```

**Comment by STRML** [comment]
Ah, you're right; we'll just reuse the RegExp for this exact purpose. Thanks.
