### ISSUE TITLE
Completely center element conflicting with applied transform

### ISSUE THREAD

**Issue by scniro** [react-grid-layout/react-draggable#223]
I had a modal leveraging this library for dragability. The size of this modal is unknown, so I initialize the style with the following rule...

    transform: translate(-50%, -50%);

this will dead center my element no matter the size. However, as soon as I start to drag, the transform kicked in by this library starts back at `translate(0, 0);` - causing the element to jump at first, then drag accordingly. 

I looked into the options such as `defaultPosition` and this works well if the height/width are *known*. Ideally, I'd like to pass percents to it, but that results in an error.

Is there a workaround for this? I've already searched through all the issues and haven't seen one that has this exact problem. Or, how can I *exactly* center an element, and begin the dragging according with the 50% offset taken into account to where the element starts on a grid?

**Comment by STRML** [comment]
Wrap your element in another element, so that the centering hack you're using does not conflict with `<Draggable>` or use another of the many options out there for centering the element (such as flexbox or margin: auto).

**Comment by eric-burel** [comment]
Hi, translating the wrapped component won't work, as the Draggable zone itself won't be translated. We need everything to be translated in this case.

Sadly, there seems to be no options to center a floating element whose width is unknown on the sreen than translating it from -50% after positionning it.
The use case is limited but legitime.

Therefore the solution is indeed to accept a string as `defaultPosititon` param. Then, we can use `calc` to compute the translation, something like this: `transform(calc(defaultPosition.x + x), calc(defaultPosition.y +y))`
