### ISSUE TITLE
Is this possible...?

### ISSUE THREAD

**Issue by tleewu** [react-grid-layout/react-draggable#225]
I'm playing with Draggable for the first time - beautiful library 💯 

Is there a way to make a Draggable component go back to its original position if it doesn't meet a requirement? For example, I want to delete a Draggable component if the user drags the component to the top left container. But if the user drags it to anywhere else, I want the component to go back to its original position.

Thanks!

**Comment by STRML** [comment]
Yes, use `<DraggableCore>` for any application where you need to manage state explicitly.
