### ISSUE TITLE
current status

### ISSUE THREAD

**Issue by rares-lupascu** [react-grid-layout/react-draggable#228]
hi

is this library dead?

**Comment by STRML** [comment]
I still use it daily in a production app. I am generally not implementing
new features, I consider it complete as it is, but bug fixes come as
needed.

**Comment by rares-lupascu** [comment]
was asking because the are a lot of opened issues from a long time ago with no answer ... i am a bit scared to use it in my apps

**Comment by STRML** [comment]
You can use it if you like. It is not a business, not a product, nobody is
making money. It is free code. Do what you wish.
