### ISSUE TITLE
Feature request : limit movement to parent element boundaries.

### ISSUE THREAD

**Issue by Delapouite** [react-grid-layout/react-draggable#23]
Hello.

Currently, there seems to have no way to restrict the area where the draggable element can move. It would be very useful to be able to limit the zone to its parents boundaries for example.

**Comment by k88hudson** [comment]
+1

**Comment by Gee63** [comment]
+1

**Comment by STRML** [comment]
This is in `0.6.0`, thanks for your patience everyone.
