### ISSUE TITLE
Allow multiple selectors for handle and cancel

### ISSUE THREAD

**Issue by romamatusevich** [react-grid-layout/react-draggable#230]
`handle` and `cancel` props allow only single selectors. What if we need to have multiple selectors for handle and cancel? For example three buttons with different selectors should initiate drag.

Possible solution is to allow an array of selectors for `handle` and `cancel`. For example:
- `handle: ['.handle', '.button', '.dragHandle']`
- `cancel: ['.cancel', '.cancelButton', '.dragCancel']`

What do you think?

**Comment by STRML** [comment]
You should be able to use `'.handle, .button, .dragHandle'` directly.

**Comment by romamatusevich** [comment]
Right, the selectors group can be in usage and no need for an array of selectors. Thank you.
