### ISSUE TITLE
drag element not work 

### ISSUE THREAD

**Issue by artem-kushal** [react-grid-layout/react-draggable#233]
I see a very strange behavior. When I try drag element in chrome I get error - Uncaught TypeError: _react2.default.cloneElement is not a function at DraggableCore.render. But if I drag element in Mozilla this work fine. Any idea how fix that behavior?
![2017-03-22_1806](https://cloud.githubusercontent.com/assets/13419905/24204963/1e88ff40-0f2b-11e7-8ae2-1bffe3774f72.png)

**Comment by STRML** [comment]
Almost certainly an outdated React version. Please reopen if you're still having issues.
