### ISSUE TITLE
Problem with event Logger

### ISSUE THREAD

**Issue by samurai404** [react-grid-layout/react-draggable#234]
![capture du 2017-03-30 10-30-10](https://cloud.githubusercontent.com/assets/20687368/24497641/04f9e7ba-1534-11e7-9223-29d17bc5cfda.png)

**Comment by STRML** [comment]
??? That's not part of `<Draggable>`, that's your code.

In your case it looks like you're using https://babeljs.io/docs/plugins/transform-class-properties/.

**Comment by samurai404** [comment]
i just copied the code from https://github.com/mzabriskie/react-draggable
and try to run with a boilerplate architecture and still don'tknow why it throws this error
