### ISSUE TITLE
Feature Request Mouse Inversion on onDrag

### ISSUE THREAD

**Issue by aestrro** [react-grid-layout/react-draggable#235]
When I have transform: rotate(180deg) as a css property being applied to a div which wraps the draggable component, I would like the mouse to not be inverted on drag, is that possible?

**Comment by trentparker16** [comment]
I have a use case for 90, 180, and 270 rotate angles.

**Comment by STRML** [comment]
Use `<DraggableCore>` and translate the coordinates you receive via callback into modified top/left or translate attributes depending on your use case.
