### ISSUE TITLE
Deprecated PropTypes reference - needs to use prop-types package

### ISSUE THREAD

**Issue by inverts** [react-grid-layout/react-draggable#243]
Looks like we've got the same PropType deprecation update to make here, noticed I still was getting the warnings because react-grid-layout depends on react-resizable and react-draggable. Won't have time to make a pull request for this one today.
(see https://github.com/STRML/react-grid-layout/issues/538 for more details)

**Comment by mixtur** [comment]
duplicate https://github.com/mzabriskie/react-draggable/issues/238

**Comment by STRML** [comment]
Fixed in 2.2.4
