### ISSUE TITLE
How to clear translate property to return to starting position

### ISSUE THREAD

**Issue by jmancherje** [react-grid-layout/react-draggable#247]
I have a component that is initialized with a top and left css property and is moved via react-draggable applying a translate x/y. Is it possible to dynamically remove the translate to return the item to it's original position? Another possibility would be setting transform back to `transform: translate(0, 0)`. Is this achievable through the react-draggable api?

**Comment by STRML** [comment]
Yes, set `position` to `{x: 0, y:0}` temporarily then clear it, reset the `key` (this will cause a remount), or use `<DraggableCore>` to control it completely.

**Comment by jmancherje** [comment]
@STRML thanks for the great suggestion. I implemented this by essentially giving it a  and it functionally works great, however because my implementation is triggering the re-render onDragStop and I am seeing this warning:

```
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Draggable component.
```

I see that setState is being called in the onDragStop in `Draggable.es6`
https://github.com/mzabriskie/react-draggable/blob/95b40d1f865c02ff9a9759fab0691ed8881ff5a8/lib/Draggable.es6#L296

If you would like I can submit a PR to prevent setting state if the component is mounting or unmounted.

**Comment by nsonnad** [comment]
I am having this same issue—would it be possible to do as @jmancherje says and prevent setting state in those cases?
