### ISSUE TITLE
typings has problem

### ISSUE THREAD

**Issue by ONEGISER** [react-grid-layout/react-draggable#251]
typings has problem

**Comment by STRML** [comment]
Care to share what that problem is?

**Comment by jorgegonzalez** [comment]
I'm getting this error in Chrome: `Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.`

I don't see anything wrong with the typings file though.

**Comment by junibrosas** [comment]
typings has problem

**Comment by beshanoe** [comment]
when using TypeScript you should write:
```typescript
import * as Draggable from 'react-draggable'
```
But this led me to another problem, TS compiler now throws an error:
`JSX element type 'Draggable' does not have any construct or call signatures.`

**Comment by beshanoe** [comment]
seems it has been solved recently #246

**Comment by STRML** [comment]
This problem has either been fixed, or there is simply too little information to debug.

"typings has problem" is not a workable ticket. Please have some respect for our time.
