### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by callmemagnus** [react-grid-layout/react-draggable#252]
The demo at this url: http://mzabriskie.github.io/react-draggable/example/

The console is showing this:

![image](https://cloud.githubusercontent.com/assets/232478/26285354/592231b0-3e4e-11e7-946d-daf6250eab06.png)

**Comment by STRML** [comment]
Not sure what to tell you - is working fine in my testing. Try a hard refresh.

**Comment by callmemagnus** [comment]
I'm stupid... That's all...
