### ISSUE TITLE
Specify initial position relative to body

### ISSUE THREAD

**Issue by austingayler** [react-grid-layout/react-draggable#259]
I'd like the default position of my draggable element to be, say, 200px down from the top of the screen and centered horizontally. Is this possible?

**Comment by STRML** [comment]
Yes, just position it that way (`position: absolute`) then apply `<Draggable>` to the element. Try it.

**Comment by austingayler** [comment]
Thanks--for anyone else coming in from google:

```
<Draggable>
    <div style={{top : '250px', left : '50%', marginLeft : '-250px', width : '500px', position : 'absolute'}}>
```
