### ISSUE TITLE
Dragging functionality disappears if child element is a React object

### ISSUE THREAD

**Issue by trbabb** [react-grid-layout/react-draggable#262]
It looks like if the child of a `Draggable` is not a native HTML element, the dragging fails. For example:

    <Draggable ...>
        <MyReactElement ... />
    </Draggable>

does not work, but 

    <Draggable  ...>
        <div>
            <MyReactElement ... />
        </div>
    </Draggable>

does. I suspect this is because React "ref" functions are passed HTML DOM nodes if the ref'd object is native, but a React element object (whose DOM node needs to be found with `ReactDOM.findDOMNode()`) otherwise. This is an annoying inconsistency in React, and I'd guess it's the culprit.

It's a bit unintuitive that this sometimes works and sometimes not. Would it be possible to fix? 
thanks!

**Comment by STRML** [comment]
See https://github.com/mzabriskie/react-draggable#draggable-api, specifically:

> For the <Draggable/> component to correctly attach itself to its child, the child element must provide support for the following props:...
