### ISSUE TITLE
minified and uglified bundle is larger than the source code

### ISSUE THREAD

**Issue by everdimension** [react-grid-layout/react-draggable#263]
Hi!

I was surprised to see that your [`dist/react-draggable.min.js`](https://github.com/mzabriskie/react-draggable/blob/267306250258ff79b942e1d1d1d87e2231dc8855/dist/react-draggable.min.js) file weighs `45.4 KB`.

This is reason enough to avoid using this package for lots of projects.

But then I wondered: where does all this code come from?

As I understand, your source code lies in the `/lib` folder. I calculated the total weight of all files there — and it is `35.62 KB`! Less than your minified bundle.

I understand that webpack transpilation adds some bloat, but still, how can a minified and uglified package be larger than the source code?

Perhaps we should look into this?

**Comment by STRML** [comment]
I believe this bundle includes React.
Honestly, I don't think it's useful to anyone and I plan to remove it from
the repo later on.

**Comment by everdimension** [comment]
No, this bundle does not include react.
Also it's kind of funny that you're unsure what it includes :)

**Comment by STRML** [comment]
This was written years ago. I have hundreds of projects in flight... easy to forget.

**Comment by STRML** [comment]
The issue is that the bundle contains the `prop-types` package and the webpack/browserify `node-process` shim.

**Comment by everdimension** [comment]
If it got included into your dist package, how can I be sure this won't be bundled into my production code when I use your module?

I'm not blaming you here, I'm saying this might be an important issue to take a closer look at.

**Comment by STRML** [comment]
It will be, but it will be reduced if you use those dependencies elsewhere.
