### ISSUE TITLE
touch-action: none shouldn't be set when react-draggable is disabled

### ISSUE THREAD

**Issue by santiagopuentep** [react-grid-layout/react-draggable#267]
The `touch-action: none` is blocking scrolling on mobile even when the `disabled` property is set to `true`.

This is not wanted in the case when you want to scroll the screen and enable react-draggable only on tap and hold.

The css shouldn't be set if `disabled: true`.

**Comment by STRML** [comment]
This should no longer be an issue with the merging of #261.
