### ISSUE TITLE
Large logfile "foo.txt"

### ISSUE THREAD

**Issue by Billy-** [react-grid-layout/react-draggable#272]
I was checking the size of all of my dependencies with cost-of-modules, and I have tracked a large module back to this, library, which has a 45 MegaByte file named "foo.txt" in the root of the module. From the contents it appears to be some sort of log.
![image](https://user-images.githubusercontent.com/4316168/29562235-5c1c9132-8730-11e7-9d98-13a280fad371.png)

**Comment by STRML** [comment]
Thanks, and sorry about that! This is fixed in 3.0.2.
