### ISSUE TITLE
onStart/onStop getting triggered by a simple click inside the element

### ISSUE THREAD

**Issue by the-noob** [react-grid-layout/react-draggable#278]
Not sure if it's expected behaviour (wasn't for me) but a simple click on a Draggable element will trigger onStart/onStop.
I would expect those to be called when some actual dragging happened (even if just to be dropped back to same position)

**Comment by STRML** [comment]
It's not really possible to know what the intention is. You can wait for a 1px movement, but that won't be right for apps where you want immediate feedback.

If you want to ensure something has actually moved, take a look at the data coming back in the callback, or just use `onDrag`.
