### ISSUE TITLE
Not Draggable when using in webpack starter

### ISSUE THREAD

**Issue by rothnic** [react-grid-layout/react-draggable#28]
I haven't been able to figure out what the issue is. It could definitely be user related. The example works fine, but when I add react-draggable to package.json and install it, a non-draggable element is the result. It looks just like the example, but the dragging events don't occur. I tried this in another starter that had a build system and saw the same problem. I'm new with using webpack, so I assume there is something going on with the build that is messing things up.

This is the webpack starter I was using: https://github.com/webpack/react-starter

I changed index.jsx to look like the following:

```
/** @jsx React.DOM */

var React = require("react"),
    Draggable = require("react-draggable");

var Display = require("./Display");
var Control = require("./Control");

var Example = React.createClass({

    handleDrag: function(el, ui) {
        console.log(ui.position);
    },

    render: function() {
        require("./style.less");
        return (
            <div>
        <div className="module-example">
            <Display />
            <div>
                <Control action="increment" label="+1" />
                <Control action="decrement" label="-1" />
                <Control action="reset" label="Reset" />
            </div>
        </div>
          <Draggable grid={[25,25]} zIndex={100} onDrag={this.handleDrag}>
            <div className="box">I can be dragged anywhere</div>
          </Draggable>
        </div>
        );
    }
});
module.exports = Example;
```

Here is what the debug window looks like:
![image](https://cloud.githubusercontent.com/assets/452052/5185364/86d7f1f8-7484-11e4-9c21-167de2c227ec.png)

**Comment by voodoohop** [comment]
did anyone find a solution? i think i'm experiencing the same thing when trying to use the react-grid-layout inside a webpack project that uses the dev-server and hot code swapping.

**Comment by rothnic** [comment]
So, I played around with using it in react-grid-layout, as well. However, I've tried using a few different webpack starters, and I'm not sure has caused the issue to go away, which makes me kind of unhappy that I can't understand what the issue is.

One key thing I had to do was install the react-grid-layout via npm directly from github. I think npm is a bit behind the github repo, or it was at the time.

Second, try [react-starter](https://github.com/webpack/react-starter). I'm not a huge fan how there are some complexities built into it that I think don't really need to be in there for a starter, but it seems to be easy to start modifying from. At first I was having some issues, but it appears they have gone away through either updates to a forked dependency of react-grid-layout, or a difference in this starter vs. the other.

I just uploaded what should be a working state for an example with react-grid-layout integrated in at [grid-dashboard](https://github.com/rothnic/grid-dashboard).

**Comment by voodoohop** [comment]
i've had some continuing strange issues that i can't reproduce. it seems when i did an npm install directly from the git reposity of react-draggable after the live reload the items were suddenly draggable as expected. but after restarting my whole project they reverted to not being draggable anymore.

if i get something reproducible i'll respond here

**Comment by raysuelzer** [comment]
Well, I should have checked the issues before spending nearly two days trying to figure out why nothing was draggable.  I'm using webpack and transformations using babel.  I still have not figured out what the problem is.

**Comment by raysuelzer** [comment]
Has anyone else been able to get this module to work with webpack?

**Comment by raysuelzer** [comment]
I believe I figured it out!!!  It should  require `var React = require('react')`  not  require('react-addons') 
.
https://github.com/mzabriskie/react-draggable/pull/41

**Comment by STRML** [comment]
We have removed the addons - thanks.
