### ISSUE TITLE
Passing in parent's handleStop to draggable children - how can I determine which child?

### ISSUE THREAD

**Issue by johnreynolds** [react-grid-layout/react-draggable#291]
I have a parent component that contains many draggable children, and I want to update the state of the parent whenever a child is moved.
I have passed the parent's handleStop to each of the children, but don't know how to determine which child has invoked it.
Thanks

**Comment by STRML** [comment]
This is more of a general React question. I've usually solved this like so:

```js
class Foo extends React.Component {

  onDragStop(childID, event, data) {
    // ...
  }
  render() {
    ...
    <Draggable onStop={this.onDragStop.bind(this, someID)}>...</Draggable>
    <Draggable onStop={this.onDragStop.bind(this, someID2)}>...</Draggable>
    ...
  }
}
```

But it depends on your needs.

**Comment by johnreynolds** [comment]
Thank you. That suites my needs perfectly.
