### ISSUE TITLE
'Cannot read property 'call' of undefined' in matchesSelector function on clicking an element within Portal which is within draggable

### ISSUE THREAD

**Issue by dmrzn** [react-grid-layout/react-draggable#300]
Hello. We have the following UI structure:
```html
<Draggable>
   <div>draggable header</div>
   <div>some regular content</div>
   <Portal>some content in portal</Portal>
</Draggable>
```
Where Portal is Portal component from https://github.com/tajo/react-portal

When mousedown event occurs in Portal - 'Cannot read property 'call' of undefined' error is thrown in matchesSelector function.

See https://codesandbox.io/s/v0nwywwlk7 for the details.

**Comment by svsool** [comment]
I have the same problem. It should be easy to fix by adding if check here:

https://github.com/mzabriskie/react-draggable/blob/c39ef7b635a0a6f81a0ee35a892d026c61da389e/lib/utils/domFns.js#L22-L23

**Comment by svsool** [comment]
I opened PR to fix this problem https://github.com/mzabriskie/react-draggable/pull/303

**Comment by Antontelesh** [comment]
@svsool won't it break when trying to access `document.parentNode` then?
Also, I see that checks failed in your PR.

**Comment by Antontelesh** [comment]
Ah, I see that `document` has `parentNode` specified to `null`. ok then. good job! :)
