### ISSUE TITLE
DraggableCore should be a PureComponent

### ISSUE THREAD

**Issue by gajus** [react-grid-layout/react-draggable#301]
Is there a reason why DraggableCore is not a [PureComponent](https://reactjs.org/docs/react-api.html#reactpurecomponent)?

**Comment by STRML** [comment]
We don't want to make any assumptions about your application, but most importantly:

PureComponent is counterproductive with components that use `children`. `this.props.children !== this.props.children`, essentially always, unless the developer has made an effort to hoist the child. If they're doing that, they can hoist the `<Draggable />` as well.

Making this a PureComponent would only introduce a `shallowCompare()` that will always fail.

**Comment by STRML** [comment]
See also https://github.com/facebook/react/issues/8669.

**Comment by gajus** [comment]
Makes sense.
