### ISSUE TITLE
How to dynamically change the dimensions of a Draggable element?

### ISSUE THREAD

**Issue by patrickryan** [react-grid-layout/react-draggable#310]
It looks like `style` attribute gets overridden automatically so I haven't been able to set `width` or 
 `height` of a Draggable element even when I try to force it.

For example, I am rendering multiple Draggable elements in a loop and would like each to have it's own dimensions based on model attributes, e.g. a garden with multiple beds of different sizes. I've tried inline CSS, wrapping the Draggable element in a div, etc. but nothing works.

```
this.props.plantings.map((planting) => {
  return(
    <Draggable grid={[10, 10]} bounds="parent" {...dragHandlers} style={{width: planting.width, height: planting.length}}>
         <span className='box'>
           {planting.crop_name}
          </span>
     </Draggable>
   )
})
```

**Comment by STRML** [comment]
You need to use the `<DraggableCore>` component and then control its lifecycle yourself, if you wish to programmatically adjust it.
