### ISSUE TITLE
Can't click input element 

### ISSUE THREAD

**Issue by dcorb** [react-grid-layout/react-draggable#314]
Try to click an `<input>` field nested inside a `<Draggable>` element. It doesn't focus (and can't type inside)

Demo case: https://codesandbox.io/s/302nwz7p3m

Only happens in Chrome, it works perfectly in Firefox.

Do you know any work-around for this issue?

**Comment by eriihine** [comment]
Run into this issue as well. Any workaround for this one yet?

Edit: Seems to work OK with IE11 as well, but not with chrome.

Edit2: Managed to workaround this with cancel selector. From the docs:

  // Specifies a selector to be used to prevent drag initialization.
  // Example: '.body' 
  cancel: string,

**Comment by dcorb** [comment]
Thanks @eriihine  !   I will try

**Comment by dcorb** [comment]
@eriihine  It works great!. Demo case with issue resolved https://codesandbox.io/s/1qv0qk8693 

Also, now the text can be selected with the mouse (before, even in Firefox instead of selecting the text, was dragging the container)

**Comment by taoxueweilong** [comment]
it works， thanks

**Comment by fforbeck** [comment]
great. Thanks!

**Comment by guzhongren** [comment]
good work 66666

**Comment by te-online** [comment]
@dcorb Thanks, it works great 😊 Would you, with this solution, still want to keep this issue open?

**Comment by dcorb** [comment]
@te-online  yep, I will close it  👍

**Comment by Alexey-Khlebnikov** [comment]
thank you very much @dcorb 
i saw your demo. it works well
good luck!
