### ISSUE TITLE
demo not working?

### ISSUE THREAD

**Issue by flyon** [react-grid-layout/react-draggable#32]
The demo is not working for me on chrome?

`Uncaught TypeError: Cannot read property '0' of undefined react-draggable.js:146
getControlPosition react-draggable.js:146
module.exports.React.createClass.handleDragStart react-draggable.js:417
boundMethod 10540963_267651446772964_1656155574_n.js:7071
....`

**Comment by ilyakrupnov** [comment]
Same issue but with IE, even IE11.

**Comment by raysuelzer** [comment]
http://mzabriskie.github.io/react-draggable/dist/dist/react-draggable.js   is a 404.

**Comment by Gee63** [comment]
had the same issue. Add position absolute to .box style

**Comment by STRML** [comment]
Fixed on master.
