### ISSUE TITLE
Move element from javascript

### ISSUE THREAD

**Issue by jgarmar** [react-grid-layout/react-draggable#34]
Hi! Is there anyway to move the draggable element without touch them? I'm trying to move to position I click.

Thanks!

**Comment by mzabriskie** [comment]
This isn't currently supported by react-draggable itself. You could easily do this on your own by setting the `top`, and `left` styles.

**Comment by jgarmar** [comment]
Ok but it seems that top and left values are stored in some place because
if I change this values and then try to drag with mouse, instantly turns
last top and left before change values, and moves with the mouse

**Comment by STRML** [comment]
This is incoming when I merge #31.

**Comment by STRML** [comment]
Fixed in 611c895d0c9f91277b4e73c4fc96d05a36ab24ed.
