### ISSUE TITLE
How to disable Draggable immediately when I use two fingers to drag the Element

### ISSUE THREAD

**Issue by zentan66** [react-grid-layout/react-draggable#364]
I have a rather troublesome problem in the project.I want to disable the Draggable component when I use two fingers to drag the Element on the mobile,so I declared a function on onStart event,if the length of property touches equal of 2,and the function will return false,but the function has called two times,and only the first call have taked effect.
What I want is disable the Draggable component when I use two fingers on the screen,and it will take effect immediately
`touchMovePreview = key => {
    if (key.touches.length == 2) {
	return false
    }
}`
`<DraggableCore onStart={evt => this.touchMovePreview(evt)} >`

**Comment by STRML** [comment]
Please reopen if this is still an issue, and use codesandbox to provide an example that exhibits the bug.
