### ISSUE TITLE
React DOM updating every instant on Drag

### ISSUE THREAD

**Issue by sreetamdas** [react-grid-layout/react-draggable#371]
I am rendering multiple `<Draggable>` nodes in my app, using an array stored in the `state`. With the help of React's Chrome extension's "Highlight Updates" I could see that all of the different nodes being rendered using a `map` function were being re-rendered/updated every instant when I would drag any single node.

This seems like something that _shouldn't_ be happening, especially considering that I used `key` prop as suggested by React while rendering a `list` of objects.

```javascript
return (
        <React.Fragment>
            {nodes.map(
                node => (
                    <Draggable
                        key={node}        // node is a unique string
                        onStop={this.handleStop}
                        onDrag={this.handleMovement}
                    >
                        <div>
                               // content
                        </div>
                    </Draggable>
               ))}
        </React.Fragment>
    );
```

**Comment by sreetamdas** [comment]
@STRML any thoughts on this?

**Comment by STRML** [comment]
Well, of course, the item you are dragging should be rerendered. And Draggable itself does not have a tight `shouldComponentUpdate` - I generally find it bad practice to implement one in libraries as it's a common source of bugs.

You can either extend the class as you import it to add a `shouldComponentUpdate` or write to its prototype if you are very worried about performance.

**Comment by sreetamdas** [comment]
@STRML of course, the item being dragged is re-rendered, but in this example, every `Draggable` component (all of the items built using `react-draggable`, each having a unique `key` as recommended) gets updated on every instance of Drag of a singular item.

Sorry for pestering you but just wanted to know if this was expected behaviour. And thanks a lot for your time!

**Comment by STRML** [comment]
Is your parent re rendering?
