### ISSUE TITLE
Duplicate identifier 'DraggableEventHandler'

### ISSUE THREAD

**Issue by elie222** [react-grid-layout/react-draggable#375]
I am getting the following error after updating to `Draggable TS 3.1.1`:

> Duplicate identifier 'DraggableEventHandler'

I see that React Resizable is causing `Draggable ^3.0.3` to be imported too. Not sure if it's related to that.

And I have `react-rnd` importing `Draggable ^3.0.5`.

**Comment by elie222** [comment]
Not sure if it's related to having two versions of the package. I also see it's defined in these two places:

https://github.com/mzabriskie/react-draggable/blob/master/lib/utils/types.js#L4

https://github.com/mzabriskie/react-draggable/blob/master/typings/index.d.ts#L21-L27

**Comment by STRML** [comment]
The first file is Flow, the second is TS. You might want to dedupe your dep tree.

**Comment by elie222** [comment]
I'm using yarn so it should already be deduped. Will try with npm.

**Comment by elie222** [comment]
Yeah. The issue is def some conflict with react-rnd. Will fork that package and see if I can get it working:

```
node_modules/react-rnd/node_modules/react-draggable/typings/index.d.ts:50:16 - error TS2300: Duplicate identifier 'DraggableCore'.

50   export class DraggableCore extends React.Component<Partial<DraggableCoreProps>, {}> {
                  ~~~~~~~~~~~~~

  node_modules/react-draggable/typings/index.d.ts:56:16
    56   export class DraggableCore extends React.Component<Partial<DraggableCoreProps>, {}> {
                      ~~~~~~~~~~~~~
    'DraggableCore' was also declared here.
```

**Comment by elie222** [comment]
Another TS/flow discrepancy:
https://github.com/mzabriskie/react-draggable/pull/376
