### ISSUE TITLE
when mouse pointer selected words(still dragging), it made their  color white, but no blue background-color

### ISSUE THREAD

**Issue by zhaoo-jing** [react-grid-layout/react-draggable#380]
it looks like those words disappeared.
But in demo, it can not select word when dragging, is there a property can solve this problem?

**Comment by Aleczhang1992** [comment]
same problem!expect the solution and reason

**Comment by Aleczhang1992** [comment]
@Zhaojing0987 
![default](https://user-images.githubusercontent.com/15828753/51069107-ad810d00-1663-11e9-98d1-337d68e51fcf.png)

**Comment by zhaoo-jing** [comment]
@Aleczhang1992 Thank you, it works!
