### ISSUE TITLE
`scale` missing in `DraggableProps`, resulting in typescript error

### ISSUE THREAD

**Issue by te-online** [react-grid-layout/react-draggable#381]
In line 19 of `typings/index.d.ts` should be added: `scale: number`.

**Comment by te-online** [comment]
I'm reopening, because I saw that this change is not in a release yet, hence it's not on npm. Would be great if we could get it into a new release. Can I help with anything regarding that? @mzabriskie

**Comment by adenflorian** [comment]
@te-online FYI, just in case you didn't know, you can reference the github repo in your `package.json` until it gets published to npm.

`yarn add https://github.com/mzabriskie/react-draggable.git`

`npm install --save https://github.com/mzabriskie/react-draggable.git`

**Comment by te-online** [comment]
@AdenFlorian Thanks for the useful hint 😊  I simply created a child-class including the missing type 😉

**Comment by STRML** [comment]
This is now released.
