### ISSUE TITLE
Allow setting styles or at least z-index

### ISSUE THREAD

**Issue by phlax** [react-grid-layout/react-draggable#383]
if you  want to have multiple windows open and be able to cycle them dynamically you need to be able to set the z-index on the draggable element. I dont understand why not just object.assign the user.styles with the default ones.

using css will not work properly here, as you need to know in advance how many windows you want (and probably a starting z-index too)

**Comment by Hoijof** [comment]
Do you mean this?

https://github.com/mzabriskie/react-draggable/blob/master/lib/Draggable.js#L379

**Comment by STRML** [comment]
Draggable allows settings your own styles on the element.
