### ISSUE TITLE
3.2.0 Breaking Change: Drag Callbacks

### ISSUE THREAD

**Issue by STRML** [react-grid-layout/react-draggable#391]
It appears there was an inadvertent breaking change in 3.2.0 relating to https://github.com/mzabriskie/react-draggable/pull/361.

Prior to 3.2.0, if a defaultPosition were present, it became the `x` and `y` present in the callback on the initial drag and subsequent to that.

In 3.2.0, the `x` and `y` received in the callback is _relative_ to the defaultPosition already passed. So if you pass a `defaultPosition` of `x: 100, y:100`and initiate`onDragStart`, the callback will contain `{x: 0, y: 0}`in the data. This makes sense if you consider`defaultPosition`to be something more like`initialOffset`, and is required if your offset is something like, for example, `{x: '10%', y: '10%'}`.

Ref: https://github.com/bokuweb/react-rnd/issues/437 and a broken build at https://circleci.com/gh/bokuweb/react-rnd/1340.

### Next Steps

Our choices:
- Is there a way to keep the old "absolute" offsets in callbacks from <= 3.1.1?
  - Percentage offsets will make this very difficult
- Release a major version instead?
- Drop the feature? A percentage-based default position can also be achieved by wrapping the `<Draggable>` in a div with a `transform: translate(10%, 10%)`.

Ping @tnrich.

**I've pulled 3.2.0 from npm** and will be releasing a 3.2.1 with just the TS export fix.

**Comment by tnrich** [comment]
A couple ideas @STRML to "keep the old "absolute" offsets in callbacks from <= 3.1.1?": 


 - It seems like we could check to see if a percentage is being passed and only then do something more like an initial offset (this might be the most seamless as it would already work with existing packages)

 - could we introduce a new param, defaultPercentagePosition (or initialPosition). This would allow us to keep the current defaultPosition functionality the way it is. Only if you added a new property initialPosition would you get what the new functionality


If neither of the above ideas seem like viable solutions, then I think a major version would be most useful to my needs.

**Comment by STRML** [comment]
I think a new param works, perhaps `positionOffset` - makes it clear that you're not pre-setting the `state` to something like `{x: 100, y: 100}`, you're offsetting the whole thing by some number or percentage and it doesn't actually affect the internal state and doesn't show up in callbacks.

**Comment by tnrich** [comment]
@strml I think that is a great plan! Do you need help implementing it?

**Comment by STRML** [comment]
Yeah, that would be great if you have the time!

**Comment by tnrich** [comment]
I've PR'd a first pass at doing this: https://github.com/mzabriskie/react-draggable/pull/393

**Comment by tnrich** [comment]
I think this can now be closed @STRML ?
