### ISSUE TITLE
Checking Collisions

### ISSUE THREAD

**Issue by bazylhorsey** [react-grid-layout/react-draggable#394]
I am developing an application feature to map out circles components of varying weights that will not overlap and will correct any overlapping when the user lets their finger off the display. I could not find any methods that allow this. Is there any way to fix this issue within react-draggable?

**Comment by yogevlahyani** [comment]
+1

**Comment by FishOrBear** [comment]
me too...

**Comment by STRML** [comment]
This is outside the scope of `<Draggable>`. You can do this by making them controlled (set a `position`, listen to event handlers and adjust `position`). But making them not overlap is complexity that is very much application-specific and will need to be handled by you.
