### ISSUE TITLE
Should DraggableCore offsetParent property be of type React.RefObject

### ISSUE THREAD

**Issue by redoz** [react-grid-layout/react-draggable#396]
I'm no React expert but I don't quite see how I'm supposed to pass a HTMLElement into a react component at render-time, as far as I can tell the best I can do is give it a RefObject but that isn't what the DraggableCore expects.

**Comment by STRML** [comment]
You should just be able to pass the RefObject's `current` property. Please re-open if this doesn't work for you, or if you have another solution.

I can't help much more than this without more detail.

**Comment by redoz** [comment]
@STRML I don't remember how I solved it either, haven't worked with that code in a year :)
