### ISSUE TITLE
Does not work in react .13

### ISSUE THREAD

**Issue by raysuelzer** [react-grid-layout/react-draggable#40]
In 0.13 I receive the error.  Likely due to depreciation of renderComponent

 "Cannot read property '__reactAutoBindMap' of null

**Comment by raysuelzer** [comment]
I've been looking at this for a few hours now and I can't seem to figure out exactly what is causing the error here.

**Comment by raysuelzer** [comment]
perhaps this: When migrating your code, you may want to use new React.cloneElement API (which is similar to React.addons.cloneWithProps but preserves key and ref and does not merge style or className automatically).

**Comment by STRML** [comment]
This should be fixed in `master`, look out for a `0.5.0` release on the horizon after some merges.
