### ISSUE TITLE
The whole page is dragged on iOS browsers

### ISSUE THREAD

**Issue by liyuanqiu** [react-grid-layout/react-draggable#406]
See the demo page's behavior on Safari(iOS12)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24999464/58305740-c678a680-7e2b-11e9-8b73-1bead0b20aab.gif)

Other browsers with the same problem:
- Chrome Mobile(iOS)
- Edge Mobile(iOS)
- Firefox Mobile(iOS)

It seems good on Android.

**Comment by mupkoo** [comment]
Take a look at the solution here -> https://github.com/mzabriskie/react-draggable/issues/279

**Comment by STRML** [comment]
Fixed in #470
