### ISSUE TITLE
Unable to type text within internal text elements

### ISSUE THREAD

**Issue by newsiberian** [react-grid-layout/react-draggable#410]
When trying to get text element (textarea) focus, it always loose after the click. The one way I found to typing text, is to keep mouse left button pressed:

![Peek 2019-06-30 01-29](https://user-images.githubusercontent.com/11130487/60388153-7d291000-9ad7-11e9-95f4-b694867b394b.gif)

**Comment by Nickdom1** [comment]
Saw the solution in a similar ticket, use the enableUserSelectHack prop:

`<Draggable
        enableUserSelectHack={false}>
        <div>
        </div>
</Draggable>`

https://github.com/mzabriskie/react-draggable/issues/384

**Comment by anuragmathur18** [comment]
Great!

**Comment by cesc1802** [comment]
I have the same issue, thanks for answer :)

**Comment by sahilpaudel-pe** [comment]
It worked for me.

**Comment by STRML** [comment]
This is fixed in #470.

**Comment by arpanpreneur** [comment]
Which version was this fixed in?
