### ISSUE TITLE
Cannot Import

### ISSUE THREAD

**Issue by SoAsEr** [react-grid-layout/react-draggable#426]
it requires ./build/draggable, but there is no build folder when I import after installing from node, only lib. As a result nothing is exported

**Comment by dave-educode** [comment]
I just started getting this error too after updating my dependencies.

**Comment by concefly** [comment]
v4.0.1 is broken. Install v3.x instead

**Comment by STRML** [comment]
Fixed in ad8b499 / 4.0.2, apologies for the disruption.
