### ISSUE TITLE
Missing of sourmap

### ISSUE THREAD

**Issue by orzyyyy** [react-grid-layout/react-draggable#428]
When working with webpack, it warns as below:

WARNING in ./node_modules/react-draggable/web/react-draggable.min.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) <b>Cannot find SourceMap 'react-draggable.min.js.map': Error: Can't resolve './react-draggable.min.js.map'</b> in '/home/orzorzorzorz/github/mini-xmind/node_modules/react-draggable/web'

**Comment by okunishinishi** [comment]
i have same error with `react-draggable@4.0.2`

**Comment by STRML** [comment]
Fixed in 4.0.3
