### ISSUE TITLE
Not working with android devices

### ISSUE THREAD

**Issue by Ricka7x** [react-grid-layout/react-draggable#429]
is there an API to make it work with touch events?
since it's not working on most android devices

**Comment by STRML** [comment]
It absolutely does work with Android devices. Feel free to re-open if you have a more targeted bug report.

**Comment by gherciu** [comment]
@STRML No it doesn't work...this library has at least 5 issues opened about it....no one can uses touch events if the element is wrapped in Draggable...it simple doesn't trigger the children touch events or somehow cancel those

**Comment by STRML** [comment]
@Gherciu The original bug report told me next to nothing about what the actual problem is - and neither have you. This is open source, if you'd like to spend some time investigating it and come up with a thorough report and/or fix, that would be very helpful.
