### ISSUE TITLE
Does not play well with touch and mouse events.

### ISSUE THREAD

**Issue by raysuelzer** [react-grid-layout/react-draggable#43]
If you are using your mouse on a touch screen laptop the mouse events will not work.  I've fixed this locally but want to wait until my other PR is pulled in before I put in another pull request.

**Comment by mminder** [comment]
+1

**Comment by STRML** [comment]
Can you check that this is fixed in `0.4.3`? I committed a fix back in January but it wasn't pulled into a release until recently.

**Comment by STRML** [comment]
Fixed in 932efd6abb545023447ac5fcb7bd1f281f44f495

**Comment by mminder** [comment]
thx!
