### ISSUE TITLE
IOS 13 breaking change with input boxes

### ISSUE THREAD

**Issue by mikegamaroff** [react-grid-layout/react-draggable#432]
IOS 13 new update no longer allows you to edit an input box, or element with an input box in it, without disabling the input box. You can still drag the input box, but it is no longer editable. Draggable text boxes are fundamental to our product, so this is a major breaking change across all IOS devices that have upgraded. Could you please investigate a fix?

Thank you!

**Comment by STRML** [comment]
Hi - this is not a common use case. I think you may be on your own to
investigate it. This is free software and we do not provide support.

**Comment by STRML** [comment]
This may have been fixed with #470 which was released as Draggable 4.3.0. Please give it a shot.
