### ISSUE TITLE
Allow `cancel` option to be given as Array

### ISSUE THREAD

**Issue by silverwind** [react-grid-layout/react-draggable#436]
`cancel` currently only allows a single selector but in complex use cases, it would be handy to specifiy multiple CSS selectors to allow fine-grained control over the elements that don't start the dragging.

This feature could be made backwards-compatible by using a `Array.isArray` check so both `string` and `Array` types could be supported.

**Comment by Spiderixius** [comment]
Hey. You are able to give it multiple options by simply separating by a comma:

For example: `cancel="button, h1">`

**Comment by silverwind** [comment]
Indeed, it looks like the string is passed to `Element.matches` which does seem to support multiple selectors separated via comma and those seem to be OR-ed together. Maybe a small docs update with this information would be helpful.

**Comment by Spiderixius** [comment]
If I don't forget I can make a PR to update the docs for that part. Otherwise, feel free to make the PR yourself :)

**Comment by silverwind** [comment]
https://github.com/mzabriskie/react-draggable/pull/446
