### ISSUE TITLE
Support `<React.StrictMode>`

### ISSUE THREAD

**Issue by wallzero** [react-grid-layout/react-draggable#440]
When using `<React.StrictMode>` I receive the following browser console error:

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Draggable which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
```

**Comment by robhicks** [comment]
This isn't fixed. It is still happening in 16.14.0.create-react-app uses <React.StrictMode> by default.

**Comment by Jack-Works** [comment]
Do you add `nodeRef`? In there is no way to know what it should reference to without findDOMNode if you don't give a ref to it. @robhicks

**Comment by robhicks** [comment]
Thanks! that fixed the issue. Perhaps something should be added to the documentation.

**Comment by 1rens1** [comment]
I have used `nodeRef` but somehow it still warns me. Any ideas?
