### ISSUE TITLE
z-index in case of multiple Draggable elements

### ISSUE THREAD

**Issue by nik10-mah** [react-grid-layout/react-draggable#448]
I am using Draggble to generate multiple draggable components on click of a button. But Each component by default overlaps the previous one. Is there a way I can bring currently being dragged component to the front when I click on it?

**Comment by Spiderixius** [comment]
Hey. I noticed when dragging the Shadow root element the element acquires a `.react-draggable-dragging` className. You could then simply in your CSS for that React component add something like this: 

```css
.react-draggable-dragging {
  z-index: 2000000000000 !important;
}
```
This will then ensure the element being dragged will always be the one on top @nik10-mah 

Hope that helps :)
