### ISSUE TITLE
Changing translate(x, y) to translate3d(x, y, z)

### ISSUE THREAD

**Issue by linlif** [react-grid-layout/react-draggable#449]
When I use like below, I can't draggable anymore ! I guess Draggable use translate(x, y) but Img tag use rotate3d().They are different dimension! So, I hope author can consider this situation, or give me a resolution will be great!

```
<Draggable>
    <div>
         <img style="transform: rotateX(45deg)"/>
    </div>
</Draggable>
```

**Comment by STRML** [comment]
There's no reason why the code you just posted wouldn't work.
