### ISSUE TITLE
Avoid collision between multiple Draggable elements.

### ISSUE THREAD

**Issue by Spiderixius** [react-grid-layout/react-draggable#452]
I would like to avoid collision between two Draggable elements. For example if I have the following two Draggable divs, I would like to avoid `Div 1` and `Div 2` to being dragged over each other:

```js
<Draggable>
  <div id="div-one">Div 1</div>
</Draggable>

<Draggable>
  <div id="div-two">Div 2</div>
</Draggable>
```
I believe I have to do something with the `bounds`, any hints or ideas?

**Comment by STRML** [comment]
Bounds won't do it. If you want to simply stop the dragging one, you'll have to listen to callbacks, know the size of your elements, and `return false` from `onDrag`.

If you want them to interact, you'll need to control them similar to the example:

https://github.com/STRML/react-draggable/blob/4b46cbab9b74e803d125e06493cb15fdb549df75/example/example.js#L154-L177
