### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by zilahir** [react-grid-layout/react-draggable#455]
in production getting the following error: 

```
Uncaught TypeError: Super expression must either be null or a function
    at react-draggable.min.js:598
    at react-draggable.min.js:597
    at Module.<anonymous> (react-draggable.min.js:504)
    at n (react-draggable.min.js:14)
    at Object.e.exports (react-draggable.min.js:93)
    at n (react-draggable.min.js:14)
    at e.exports (react-draggable.min.js:50)
    at Object.<anonymous> (react-draggable.min.js:4)
    at i (index.html:1)
```

any idea how to solve this?

**Comment by STRML** [comment]
Not a bug in react-draggable. Probably in how you are bundling. Can't possibly diagnose or provide general application support, sorry.

**Comment by Summer-andy** [comment]
hello， how to solove it?

> in production getting the following error:
> 
> ```
> Uncaught TypeError: Super expression must either be null or a function
>     at react-draggable.min.js:598
>     at react-draggable.min.js:597
>     at Module.<anonymous> (react-draggable.min.js:504)
>     at n (react-draggable.min.js:14)
>     at Object.e.exports (react-draggable.min.js:93)
>     at n (react-draggable.min.js:14)
>     at e.exports (react-draggable.min.js:50)
>     at Object.<anonymous> (react-draggable.min.js:4)
>     at i (index.html:1)
> ```
> 
> any idea how to solve this?

how to solve it?
