### ISSUE TITLE
Discrepancy of X,Y position of Draggable in comparison to e.clientX and e.clientY positions.

### ISSUE THREAD

**Issue by justinbaltazar** [react-grid-layout/react-draggable#456]
How does Draggable calculate its position? I've noticed with my app there seems to be a discrepancy in how X and Y positions are calculated by Draggable in comparison to how these coordinates are normally handled.

**Comment by abv** [comment]
x and y refer to the mouse position. offsetX and offsetY refer to the mouse position relative to the draggable. to get the actual position subtract the offset from x & y.

```
onDraggableStop = (...args) => {
    const {x, y, offsetX, offsetY} = args[0];
    console.log({x: x - offsetX, y: y - offsetY})
}
```
