### ISSUE TITLE
Question about the library

### ISSUE THREAD

**Issue by kuttim** [react-grid-layout/react-draggable#461]
Hey, I have multiple divs, and let's say if I would drag one div for example, right side, the other div which was already on right side, would move itself to left, is it possible to do something like that?

If so, can somebody perhaps enlighten me how to go about it?

My current code for the draggable itself.
```
const dragHandlers = {onStart: this.onStart, onStop: this.onStop};
      data.push(
        <Draggable bounds={{top: -100, left: -100, right: 100, bottom: 100}} {...dragHandlers}>
        <div class="square-lookbook"
          style={{ backgroundImage: `url(${url})` }}
          key={i}
        ></div>
     </Draggable>
```

**Comment by STRML** [comment]
Yes, see the controlled component example at https://github.com/STRML/react-draggable/blob/4b46cbab9b74e803d125e06493cb15fdb549df75/example/example.js#L32-L38 and https://github.com/STRML/react-draggable/blob/4b46cbab9b74e803d125e06493cb15fdb549df75/example/example.js#L154-L177. 

You can view the demo live at http://strml.github.io/react-draggable/example/
