### ISSUE TITLE
Dragging causes logging in console

### ISSUE THREAD

**Issue by arkhvoid** [react-grid-layout/react-draggable#471]
Noticed that current version 4.3.0 will log 'DraggableCore' stuff in console while dragging element.

**Comment by wenerme** [comment]
4.3.0 also not works with grid-layout, took my half day to find out, seems the style not pass down to child. pin to 4.2.0 solved

**Comment by STRML** [comment]
Woof. Thanks all, unpublishing and will fix this in 4.3.1 soon (i.e. not on a holiday).

**Comment by STRML** [comment]
The curiosity was killing me. Both issues were quite strange (cache invalidation and what appears to be a bug in `React.cloneElement`). They are both fixed in `4.3.1`.

Unfortunately I couldn't pull 4.3.0 as something is depending on it, but I've added a deprecation message.
