### ISSUE TITLE
v4.3.1: Super expression must either be null or a function

### ISSUE THREAD

**Issue by xiaodi0003** [react-grid-layout/react-draggable#472]
when use v4.3.1, console error: Super expression must either be null or a functio...
v4.2.0 is ok

**Comment by STRML** [comment]
Do you have a stacktrace? I am not seeing this error.

**Comment by andreitarasov-dev** [comment]
I'm using `react-draggable` with `react-resizable`. This is what I have in console

```
Uncaught TypeError: Super expression must either be null or a function
at react-draggable.min.js:537
at react-draggable.min.js:536
at Module.<anonymous> (react-draggable.min.js:535)
at n (react-draggable.min.js:15)
at Object.e.exports (react-draggable.min.js:88)
at n (react-draggable.min.js:15)
at e.exports (react-draggable.min.js:51)
at Object.<anonymous> (react-draggable.min.js:5)
at f ((index):1)
at Object.<anonymous> (Resizable.js:10)
```

**Comment by Jordan-Eckowitz** [comment]
@STRML, I am getting the same error in my production build:

![image](https://user-images.githubusercontent.com/19767538/79140100-7842fd80-7d85-11ea-9051-c7d67f4bb233.png)

**Comment by dan7554** [comment]
Same error with react-grid-layout ~0.18.3

**Comment by dan7554** [comment]
Determined it was a build server caching issues with us.

**Comment by STRML** [comment]
Can you get an example of this happening in codesandbox or debug further? I cannot replicate this.

**Comment by huanle0610** [comment]
It happens only in production version. [codesandbox link](https://codesandbox.io/s/draggable-9oqwl)
build it or deploy it to see "console error: Super...."

**Comment by STRML** [comment]
By chance, are any of you using terser? https://github.com/terser/terser/issues/308

**Comment by mattogren** [comment]
We're experiencing this issue and we're using terser:
terser@^4.1.2
terser-webpack-plugin "^1.4.1"

We've pinned to 4.2.0 for now...

**Comment by dennisvankekem** [comment]
same issue, but not using terser at our side.

**Comment by Zwieks** [comment]
Same issue here:
 "react-grid-layout": "^0.18.3",
 "react-draggable": "^4.2.0",
 "react-resizable": "^1.10.1",
Not using Terser
Blocking a production build..

**Comment by jelafi** [comment]
Same issue here.

I forked:
"react-grid-layout": "0.16.9" 
containing in the package.json:
"react-draggable": "3.x"
"react-resizable":"1.x"
what leads to the lock of react-draggable in version 3.3.2 and 4.3.1

I then use this fork into a package built with webpack.
The final application is using this package and builds correctly but I have the exact same error in the browser console at application startup.

Everything is working fine if I pin 4.2.0 or use npm start for the final application.

**Comment by krotsky** [comment]
> Same issue here:
> "react-grid-layout": "^0.18.3",
> "react-draggable": "^4.2.0",
> "react-resizable": "^1.10.1",
> Not using Terser
> Blocking a production build..

I've changed "react-draggable" to "4.2.0" (without ^), it works

**Comment by SmithaHS** [comment]
Facing the same issue suddenly. Works fine in Dev env but fails on Prod. Any rootcause? because there was no change in package.json done and no change in code as well.

**Comment by andreitarasov-dev** [comment]
> Facing the same issue suddenly. Works fine in Dev env but fails on Prod. Any rootcause? because there was no change in package.json done and no change in code as well.

Check your package.json. If you have "react-draggable": "*" or "^4.2.0", you will have a new broken version automatically when running `npm install`.

Specify explicitly the working version like "react-draggable": "4.2.0"

**Comment by SmithaHS** [comment]
> > Facing the same issue suddenly. Works fine in Dev env but fails on Prod. Any rootcause? because there was no change in package.json done and no change in code as well.
> 
> Check your package.json. If you have "react-draggable": "*" or "^4.2.0", you will have a new broken version automatically when running `npm install`.
> 
> Specify explicitly the working version like "react-draggable": "4.2.0"

Yes, added it explicitly and it works fine with that. Wanted to root cause it. Have not mentioned react-draggable separately in package.json.

**Comment by nelsondude** [comment]
Same issue here. Using terser and uglify - i think it can be fixed by setting f_names=true in terser config but this feels like a hack

**Comment by Chnapy** [comment]
Same here, since an upgrade from 3.x to 4.3.1.
![image](https://user-images.githubusercontent.com/7474483/80725274-24fdd880-8b03-11ea-9d76-ac14a9b8e84b.png)

Rollback to 4.2.0 resolved the issue.

**Comment by nelsondude** [comment]
Any chance we can do a patch that rolls back 4.3.1 version until root cause is found?

**Comment by dan7554** [comment]
If you are using an old version, try upgrading to the latest version.

**Comment by STRML** [comment]
The issue is, there were zero packaging changes made between these
versions. I don't know what we need to rollback.

If someone could *please* get a reproduction working (I have not been able to), then I can bisect and push a patch fast.

**Comment by BoazKG93** [comment]
I'm also experiencing this problem now. The weird thing is that on localhost it all works good, but once i deploy to Firebase or AWS Amplify, I get this problem. You can see it here:
https://treedis-app.web.app/login

**Comment by BoazKG93** [comment]
> Determined it was a build server caching issues with us.

So did you solve the issue? I'm also experiencing this problem only on my build server, while on localhost it's fine.

**Comment by STRML** [comment]
Thanks for that, any chance you can reproduce it locally too?

That minified file is *very* oddly formatted, my inspector can barely keep up with the execution path, and running it through a niceifier (like jsnice) completely changes the ordering of the file. It looks like Terser is getting a little too clever for its own good.

**Comment by BoazKG93** [comment]
I'll try to reproduce, although i don't have terser on my local install. so it will need some configurations. For now I also reverted to 4.2.0 which seems to work (a different link, i'll keep this broken link alive so you can use it for debugging)

**Comment by anoopfrancis09** [comment]
Is there any fix for it?
Even after setting the version to 4.2.0 didn't work for me. 
Just changing the version in package.json works? or do I need to do anything else?

My production build is blocked due to this issue.

**Comment by arielhernandezmusa** [comment]
Hi there, same issue here

**Comment by STRML** [comment]
Hi. We still need a reproduction for this issue if we are going to fix it.

**Comment by nelsondude** [comment]
Looking at https://github.com/facebook/create-react-app/issues/7236#issuecomment-504755579 , ` It looks like the library author is minifying their code, which I think contributes to the issue (really, this shouldn't be needed as the client's Webpack config does it).`

I'm not sure what the exact issue is but it sounds like if we set webpack mode to "none" and remove the optimization config then it should solve the problem. He makes a good point that the client will be minimizing anyways so this is unnecessary to include. Thoughts on this?

**Comment by nelsondude** [comment]
@STRML this probably relates to your comment earlier referencing https://github.com/terser/terser/issues/308

**Comment by STRML** [comment]
I've published `v4.4.0`, everyone who is having this problem, please give it a shot?

**Comment by procedular** [comment]
Seems fixed. We encountered the problem, when using react-rnd (which uses react-draggable) and I can confirm that your new version is working for us.

Further information: As @nelsondude mentioned, the terser-webpack-plugin, that will be integrated as a build step, when running webpack in production mode had an issue and we could solve it by upgrading terser to the latest version... But your fix works even with the broken terser version.

@STRML If you are still trying to reproduce the issue, I could help you.

**Comment by STRML** [comment]
This is fixed in `4.4.1`.

Thanks all for your patience with me, I had a hare-brained idea to modernize the builds I was shipping to support umd, cjs, and modules - an exercise in futility to handle well, with the costs far outweighing the benefits. Most of that work is deleted in `4.4.1`, and the only exposed build is ES5-compliant, unminified, CJS source.

**Comment by han-so1omon** [comment]
This appears to still be an issue. Using next 13.4.1, React 18.2.0, react-grid-layout 18.2.0, react-draggable ^4.4.1

Simple app with one page file that looks as follows:


```
import React from 'react';
import { WidthProvider, Responsive } from 'react-grid-layout';
import 'react-grid-layout/css/styles.css';
import 'react-resizable/css/styles.css';

const ResponsiveGridLayout = WidthProvider(Responsive);

const initialLayout = [
  { i: 'a', x: 0, y: 0, w: 1, h: 2 },
  { i: 'b', x: 1, y: 0, w: 3, h: 2 },
  { i: 'c', x: 4, y: 0, w: 1, h: 2 }
];

const TanGridElement = (props) => (
  <div
    style={{
      backgroundColor: 'tan',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    }}
    {...props}
  >
    {props.children}
  </div>
);

const MyComponent = () => {
  return (<div></div>);
  /*
  return (
    <ResponsiveGridLayout
      className="layout"
      layouts={{ lg: initialLayout }}
      rowHeight={30}
      breakpoints={{ lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 }}
      cols={{ lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 }}
      isDraggable={true}
      isResizable={true}
    >
      <TanGridElement key="a">A</TanGridElement>
      <TanGridElement key="b">B</TanGridElement>
      <TanGridElement key="c">C</TanGridElement>
    </ResponsiveGridLayout>
  );
  */
};

export default MyComponent;

```

This yields:

```
- error node_modules/react-draggable/build/cjs/DraggableCore.js (48:112) @ _inherits
- error Error [TypeError]: Super expression must either be null or a function
    at _inherits (webpack-internal:///(sc_server)/./node_modules/react-draggable/build/cjs/DraggableCore.js:137:15)
    at eval (webpack-internal:///(sc_server)/./node_modules/react-draggable/build/cjs/DraggableCore.js:263:5)
    at eval (webpack-internal:///(sc_server)/./node_modules/react-draggable/build/cjs/DraggableCore.js:473:2)
    at (sc_server)/./node_modules/react-draggable/build/cjs/DraggableCore.js (/Users/Shared/p/test/.next/server/app/page.js:2273:1)
    at __webpack_require__ (/Users/Shared/p/test/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./node_modules/react-draggable/build/cjs/Draggable.js:27:45)
    at (sc_server)/./node_modules/react-draggable/build/cjs/Draggable.js (/Users/Shared/p/test/.next/server/app/page.js:2262:1)
    at __webpack_require__ (/Users/Shared/p/test/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./node_modules/react-draggable/build/cjs/cjs.js:2:16)
    at (sc_server)/./node_modules/react-draggable/build/cjs/cjs.js (/Users/Shared/p/test/.next/server/app/page.js:2284:1) {
  digest: undefined
```

**Comment by LukePetko** [comment]
Same issue here

**Comment by LukePetko** [comment]
For me `"use client"` solved the issue

**Comment by BoxedFruits** [comment]
> For me `"use client"` solved the issue

Thank you so much for this! It was not working with Nextjs13 for me until adding this line. Which kind of sucks since I really wanted my project to be SSR
