### ISSUE TITLE
Not triggering onClick from inside Draggable component

### ISSUE THREAD

**Issue by carlos-algms** [react-grid-layout/react-draggable#481]
## onClick events are not being triggered from inside Draggable component

`<a>` elements do not trigger clicks 
but `<button>` does.

It is impacting components like Gatsby `Link`, that generates an `<a>` component but also uses click under the hood. 

Reproducible example: 
https://codesandbox.io/s/peaceful-northcutt-eghv8?file=/src/App.js

**Comment by ghost** [comment]
I've got a similar issue but not even the button is registering an onClick event. Running react-draggable v4.4.3

**Comment by canercandan** [comment]
Same issue here, button element with an onClick event not triggered, I tried to select the button by pressing TAB until the button is selected and then ENTER and the onClick event get triggered.

**Comment by STRML** [comment]
You may note, that the `onClick` handler is not triggered *outside* of the `<Draggable>`, either. 

Removing the trailing `/` from the `href` fixes the issue. This is not a `<Draggable>` bug.
