### ISSUE TITLE
v4.4.1: packaging error

### ISSUE THREAD

**Issue by dkuhnert** [react-grid-layout/react-draggable#482]
Hi,
When packaging using rollup the build currently breaks because the `module` property is still set in the `package.json` (https://github.com/STRML/react-draggable/blob/v4.4.1/package.json#L6) but the `build/module` directory isn't in the npm package anymore.

My assumption is that this line should have been deleted in fa030e27f3130e1077da58720f5449d3dd36986e

**Comment by magnetnation** [comment]
Same error here. Rollup build is broken now.

**Comment by STRML** [comment]
Thanks -- published `4.4.2` which fixes this.
