### ISSUE TITLE
onClick events not being triggered inside of Draggable

### ISSUE THREAD

**Issue by ghost** [react-grid-layout/react-draggable#495]
Similar to issue #481, I'm having trouble getting clicks to register inside of draggable components. The poster of #481 was able to get button clicks to register but not even this works for me when I copy the code into a live-react-app. 

Reproducible example:
https://codesandbox.io/s/peaceful-northcutt-eghv8?file=/src/App.js

The example above somehow registers button clicks but when I copy the files into a live-react-app, the buttons no longer registers clicks.

**Comment by STRML** [comment]
Why did you open a new issue if this is the same bug? Closing as a duplicate of #481.

**Comment by sujiangyin** [comment]
```
I meet the same pro,and what should i do now?


`// index.js
<Draggable
    axis="both"
    handle=".handle"
    defaultPosition={{ x: 0, y: 0 }}
    position={positionXY}
    bounds="html"
    offsetParent={document.body}
    scale={1}
    onStop={handleDragStop}
  >
    <div className="handle">
      <Box></Box>
    </div>
</Draggable>


//Box.js
<div onClick={handleClickBox}>
</div>`
```
