### ISSUE TITLE
TypeError: _reactDom.default.findDOMNode is not a function

### ISSUE THREAD

**Issue by u-prashanth** [react-grid-layout/react-draggable#505]
Hello @STRML , could you help me with this error? I'm getting this error, I don't understand the problem: I'm using [react-mosaic-component](https://github.com/nomcopter/react-mosaic) for rendering windows. Also axis drag restriction is not working, I can drag on both axis regardless of me passing axis to props.

![flow](https://user-images.githubusercontent.com/44055729/88410336-e458e700-cdf3-11ea-9d49-84a06c726c30.PNG)

### Components: Index, GraphEditor
**Index is root component with GraphEditor as its child.** The one which is working is commented inside render function.

If I just render without react-mosic it works, if I use react-mosic it give me this error: **TypeError: _reactDom.default.findDOMNode is not a function**

### Index- Component
```typescript
    render()
    {
        const ELEMENT_MAP: { [viewId: string]: JSX.Element } = {
            a: <div>Left Window</div>,
            b: <GraphEditor />, 
            c: <div>Bottom Right Window</div>,
        };

        return (
            <>
                <Wrapper>
                    {/* <CreateRouteButton onClick={this.CreateRoute}>Create Route</CreateRouteButton> */}
                    {/* <GraphEditor />  This is working fine*/}
                    {/* <LayoutGrid /> */}
                    <Mosaic<string> 
                        renderTile={(id) => ELEMENT_MAP[id]}
                        initialValue={{
                            direction: 'row',
                            first: 'a',
                            second: {
                                direction: 'column',
                                first: 'b',
                                second: 'c'
                            },
                            splitPercentage: 40
                        }}
                    />
                </Wrapper>
            </>
        )
    }
```

### GraphEditor - Component
```typescript
    render()
    {
        const { scale, position, transformOrigin } = this.state
        return (
            <GraphEditorContainer>
                <CanvasWrapper id="snap-editor">
                    <CanvasScaler className="fg-canvas" scale={scale} onWheel={this.CanvasZoomHandler} onContextMenu={e => e.preventDefault()}>
                        <Draggable axis={'x'} scale={scale} onStart={this.OnStart}  onDrag={this.OnDrag} position={position} onStop={this.OnStop} allowAnyClick>
                            <Canvas className="canvas-handle">
                                <NodeGUI scale={this.state.scale}/>
                                <NodeGUI scale={this.state.scale}/>
                                <NodeGUI scale={this.state.scale}/>
                            </Canvas>
                        </Draggable>
                    </CanvasScaler>
                </CanvasWrapper> 
            </GraphEditorContainer>
        )
    }
```

**Comment by STRML** [comment]
React-mosaic is not related to this project, at all. Mosaic uses react-dnd.

**Comment by STRML** [comment]
Try using [nodeRef](https://github.com/STRML/react-draggable/blob/fc26ec1bc75bc18964b5dbf3a8770de386e38c66/lib/DraggableCore.js#L266) if you're able to get a handle on the actual DOM element that `<Canvas>` uses. If present, `ReactDOM.findDOMNode()` won't be called.

Other than that, I don't know. Sounds like a problem with your bundler.

**Comment by u-prashanth** [comment]
@STRML Thank you for the response! Sure, I will definitely try your solution. 👍 😊
