### ISSUE TITLE
Request for enhancement, initial position.

### ISSUE THREAD

**Issue by GirlBossRush** [react-grid-layout/react-draggable#52]
I'm able to set the initial `Draggable` child component's position using a style `absolute` positioning. The `Draggable` component will then make translate transforms based off this initial position. The issue with this approach is that I'm unable to store the updated position directly.

Would it be possible to add a `start` prop to the `Draggable` component to set the initial position? I've attempted to set the child `transform` style on first render, but the `Draggable` component is not aware of this. 

Here's a link to how I'm currently fleshing out a window system using your component.
https://github.com/nirrius/nirrius/blob/master/app/common/pane/index.jsx#L55-L69
http://nirri.us/~teffen

Thank you.

**Comment by STRML** [comment]
This is a problem with the callbacks, no? The `ui.position` property reflects relative position, not absolute. You can simply add the initial absolute position to the relative position and you should get what you want.

**Comment by STRML** [comment]
I'm actually going to need something like this for [react-grid-layout](https://github.com/STRML/react-grid-layout), so expect this soon.
