### ISSUE TITLE
I cannot use "transform" on child element because Draggable override it.

### ISSUE THREAD

**Issue by bique14** [react-grid-layout/react-draggable#521]
Here is my code
```
<Draggable
   bounds={{ top: -100, left: -100, right: 100, bottom: 100 }}
   {...dragHandlers}
>
    <pre className="absolute text-white leading-8"
      id="text-preview"
      style={{ transform: `rotate(${textConfig.rotate}deg)` }}
    >
        {description}
     </pre>
</Draggable>
```

When I drag it works fine. but in the Chrome inspect element I cannot see style `transform: rotate(${textConfig.rotate}deg)` on pre tag, because it overrides by Draggable to `transform: translate(.....)` 

How can I fix it?

**Comment by bique14** [comment]
Ok, I solved this problem by wrap Draggable by `div`.

```
<div style={{ transform: `rotate(${textConfig.rotate}deg)` }}>
   <Draggable
      bounds={{ top: -100, left: -100, right: 100, bottom: 100 }}
      {...dragHandlers}
   >
       <pre className="absolute text-white leading-8"
         id="text-preview"
       >
           {description}
        </pre>
   </Draggable>
</div>
```

But is it correct ?

**Comment by STRML** [comment]
Yes, that is the best way to do it. You can't use `transform` in the style prop because Draggable needs control of it.

**Comment by lulupy** [comment]
maybe it will not work correctly; because if you set a rotate, you will get wrong drag deltas;  for example, if you set `transform: scale(0.5)` on the parent div, you need set the scale prop to ensure the drag deltas is right.
