### ISSUE TITLE
Error: <DraggableCore> not mounted on DragStart!

### ISSUE THREAD

**Issue by a-y-u-s-h** [react-grid-layout/react-draggable#527]
Things were working fine until yesterday. I did no change in the usage of my component. Simply re-run storybook and saw this error:

![2020-10-17_01-07-28_screenshot](https://user-images.githubusercontent.com/19586719/96301706-2ec5ba80-1015-11eb-8679-deb68b15c8d8.png)

**Comment by a-y-u-s-h** [comment]
Nevermind, the reason was that I was passing an element which was failing to render because maybe the props which get injected by Draggable aren't valid Theme UI styles - 

```jsx
export const Element = React.forwardRef(({ children, ...props }, ref) => {
  const options = { ...skeleton.element, ...props }
  return (
    <Box ref={ref} {...props} sx={options}>
      {children}
    </Box>
  )
})
```

**Comment by gauravsbagul** [comment]
@a-y-u-s-h  Bro I am having same issue, it was working till now. and suddenly I am getting this issue, I am using `react-resizable` and `react-draggable` is dependency of `react-resizable` I am still getting an error,
``` 
import React from 'react';
import cx from 'classnames';
import PropTypes from 'prop-types';
import { ResizableBox } from 'react-resizable';
import styles from './index.module.scss';

const ResizableContainer = ({ children, ...rest }) => {
	return (
		<ResizableBox
			{...rest}
			handle={h => {
				return (
					<div className={cx(styles.resizeBarHorizontal)}>
						<div className={cx(styles.customHandle,)} />
					</div>
				);
			}}
		>
			{children}
		</ResizableBox>
	);
};
```
Error:
``` <DraggableCore> not mounted on DragStart!```

**Comment by coolRoger** [comment]
@gauravsbagul Bro, did you fixed this error at the end? I got this error too

**Comment by gauravsbagul** [comment]
> @gauravsbagul Bro, did you fixed this error at the end? I got this error too
NO, Not yet

**Comment by gauravsbagul** [comment]
@coolRoger  No, not yet bro...

**Comment by MarksPoint** [comment]
Hi bros,
I see you run into this error as well. Please check out my related issue to see if my temp solution works for you as well. And maybe add to that thread if you've got more information?
https://github.com/react-grid-layout/react-grid-layout/issues/1732

**Comment by devgodeth** [comment]
Bro, bro and broseph, same issue here, I think it has something to do with using a custom component inside of the grid layout. something with passing `ref` as a prop. i'm going to try downgrading as a fix for now though.

**Comment by EthenThinkful** [comment]
![fixed-Error-DraggableCore-not-mounted-on-DragStart!](https://user-images.githubusercontent.com/104235709/217935588-5c8fba1f-d229-4f0a-92e6-28e4eed6f0b4.PNG)

Hey guys I know it's been a lil while but I found a solution to this. You have to add a span with it's nodeRef key set from a "ref" key because the dom does not support any uppercase names. I'm a junior developer so I'm not 100% about the technical of how it works but it works. Hope this helps!

**Comment by mariusrak** [comment]
You can also use forwarding refs https://reactjs.org/docs/forwarding-refs.html
