### ISSUE TITLE
Add threshold

### ISSUE THREAD

**Issue by sdemjanenko** [react-grid-layout/react-draggable#54]
I would like to be able to not trigger onStart unless the user has dragged more than 20 pixels (this should be configurable).

**Comment by STRML** [comment]
Happy to accept a PR for this.

**Comment by STRML** [comment]
See the [implementation of the grid property](https://github.com/mzabriskie/react-draggable/blob/bb020a48c13d1fa69796557b2b04ad105a6c29d4/lib/Draggable.es6#L187) for some hints on how to do this. If you return false from your `onDrag` handler, the element won't move.
