### ISSUE TITLE
A couple of small performance related issues

### ISSUE THREAD

**Issue by avoskresensky** [react-grid-layout/react-draggable#554]
We're working on polishing our product performance-wise, and have identified a couple of small issues with this (awesome!) library that we'd like you guys to address. Luckily, both are pretty trivial to fix:

1.
![image](https://user-images.githubusercontent.com/10179521/114971440-2b2eb700-9e31-11eb-81cf-a1bc75fb9ecc.png)

This one originates here:
https://github.com/react-grid-layout/react-draggable/blob/master/lib/Draggable.js#L239

An unconditional setState in a lifecycle. Something like this would fix that:
```
componentWillUnmount() {
    if (this.state.dragging) {
        this.setState({dragging: false}); // prevents invariant if unmounted while dragging
    }
}
```

2.
Sometimes we get "forced reflow" alerts like these:

![image](https://user-images.githubusercontent.com/10179521/114974391-24a33e00-9e37-11eb-9159-ae8f83b75360.png)

Those originates here:
https://github.com/react-grid-layout/react-draggable/blob/master/lib/DraggableCore.js#L261

Wrapping the DOM mutation in a rAF would fix that:
```
if (this.props.enableUserSelectHack) {
    requestAnimationFrame(() => {
        removeUserSelectStyles(ownerDocument);
    });
}
```

**Comment by STRML** [comment]
Sounds good, could you submit a PR for these changes?

**Comment by SheldonWatson** [comment]
> We're working on polishing our product performance-wise, and have identified a couple of small issues with this (awesome!) library that we'd like you guys to address. Luckily, both are pretty trivial to fix:
> 
> 
> ![image](https://user-images.githubusercontent.com/10179521/114971440-2b2eb700-9e31-11eb-81cf-a1bc75fb9ecc.png)
> 
> This one originates here: https://github.com/react-grid-layout/react-draggable/blob/master/lib/Draggable.js#L239
> 
> An unconditional setState in a lifecycle. Something like this would fix that:
> 
> ```
> componentWillUnmount() {
>     if (this.state.dragging) {
>         this.setState({dragging: false}); // prevents invariant if unmounted while dragging
>     }
> }
> ```
> 
> 
> Sometimes we get "forced reflow" alerts like these:
> 
> ![image](https://user-images.githubusercontent.com/10179521/114974391-24a33e00-9e37-11eb-9159-ae8f83b75360.png)
> 
> Those originates here: https://github.com/react-grid-layout/react-draggable/blob/master/lib/DraggableCore.js#L261
> 
> Wrapping the DOM mutation in a rAF would fix that:
> 
> ```
> if (this.props.enableUserSelectHack) {
>     requestAnimationFrame(() => {
>         removeUserSelectStyles(ownerDocument);
>     });
> }
> ```

I also met this problem, when can it be fixed?
