### ISSUE TITLE
How to bring the currently-being-dragged element to the front layer? z-index doesn't work

### ISSUE THREAD

**Issue by nomanoff** [react-grid-layout/react-draggable#557]
I have a multiple draggable elements and I am trying to bring the currently being dragged element to the front layer while I am dragging that element.

**Comment by sankarnarayanansr** [comment]
Assign dynamic zindex to your elements. Update maximum zindex ondragstart.

**Comment by dadlaniTarun** [comment]
@adityasreeram007 i thought about this but how?

**Comment by sankarnarayanansr** [comment]
> @adityasreeram007 i thought about this but how?

Use inline styling for your component. Dynamically assign zindex from state

**Comment by LucasBoscariole** [comment]
https://github.com/react-grid-layout/react-draggable/issues/402

Has a discution on it, you might be able to find a solution there.
