### ISSUE TITLE
Make elements independent of each other

### ISSUE THREAD

**Issue by zkwsk** [react-grid-layout/react-draggable#566]
I'm combining `Draggable` and `ResizableBox` together to make a layout where you can freely drag and resize images.

My problem is that whenever I add a 2nd image it always start under the first one and if I want to set the top bound to 0, this means that the 2nd image can never go further up than the bottom of the first component.

In addition, if I resize the first image it will affect the y position of the 2nd one.

Is there a prop I'm missing or some styling that can make them fully independent of each others position?

**Comment by STRML** [comment]
Try making all your items `position: absolute` in your css. They should then all start at the same position, then you can use `Draggable` to set their initial position relative to the same `0,0`.

**Comment by zkwsk** [comment]
Thank you, worked perfectly!
