### ISSUE TITLE
Not working with nested component

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [react-grid-layout/react-draggable#585]
The following code should work, but the rendered element is not draggable:
```jsx
<Draggable nodeRef={ref1}>
  <Component1 ref={ref1} />
</Draggable>
```

Link to reproducible example: https://codesandbox.io/s/react-draggable-bug-o4g5c?file=/src/App.js

The following example's controlled position doesn't work: https://codesandbox.io/s/react-draggable-bug-2-hy4iz

**Comment by STRML** [comment]
Hey there. You need to forward props. This wasn't super clear so I've added a mention of this to the README in 781ef77 and a test in 279ace8e3b16e2431a0ee9c2379e7fe6a4926682.
