### ISSUE TITLE
Drop detection - onMouseEnter and onMouseLeave not firing during drag

### ISSUE THREAD

**Issue by datoslabs** [react-grid-layout/react-draggable#589]
Thank you for adding drop-detection to the examples.  When I tried to replicate the same logic in my code by adding `onMouseEnter` and `onMouseLeave` to the `div` wrapped inside `DraggableCore`, it appears that those events have been suppressed during drag and are not firing when I try to drag over other `DraggableCore` components over it.  When there is no drag event, both events fire correctly.  Are there additional properties I need to add to the `DraggableCore` to enable those listeners?

Also the demo does not seem to reflect these additions, could it be that the site is outdated?

**Comment by datoslabs** [comment]
Sharing my findings in case if anyone encountered similar problems.  It appears that the reason `onMouseEnter` and `onMouseLeave` appear to be suppressed during drag is because of the higher `z-index` value of the `Draggable` than the `"Dropzone"`.  The `z-index` value of the item being dragged is increased in `onDragStartStart` in order to ensure `Draggable` item is always visible, as such, the `"Dropzone"` `z-index` is less than the `Draggable` `z-index` thus the `onMouseEnter` and `onMouseLeave` of the `"Dropzone"` is not getting called.

**Comment by msueping** [comment]
@datoslabs, were you ever able to overcome this problem?

I'm facing a similar issue with the <Draggable>. I want to detect the "dropzone" div id that would be under the dragged element but I can't find a way to do that. I've tried calling an onDrag function but the event parameter never gets the correct target dropzone. It starts with the initial zone's id but fails to change if dropped over a different div dropzone.

**Comment by datoslabs** [comment]
Are you trying to find the "dropzone's" `id` after the drop is complete?

**Comment by msueping** [comment]
> Are you trying to find the "dropzone's" `id` after the drop is complete?

I have multiple dropzones all having unique ids. I'm trying to determine the dropzone's id that the dragged element is over and just prior to it being dropped. I suppose it doesn't matter if I get the dropzone's id after the drop is done just so long as I can get it.

**Comment by datoslabs** [comment]
It's been awhile so I don't recall how I resolved this; however, looking at the example in this repo, it appears the latest version of the library addressed the issue I reported.  Look for `onDropAreaMouseEnter` and `onDropAreaMouseLeave` methods, you should be able to get the `id` from the `event` object if you need to get it before the drop and reset after it leaves without dropping.  Alternatively, you could use `onDrop` and get the child `div` from `e.target` or if you want to avoid traversing Dom, you can pass it in like `(e)=>this.onDrop(e, some_id)`.

**Comment by msueping** [comment]
Thanks for those suggestions. I'll take a look at each of them. 

Is it me or do those methods not exist in the latest version (4.4.5). I searched Draggable.js and DraggableCore.js and I do not see any reference to them. Furthermore, I'd read in another post (https://github.com/react-grid-layout/react-draggable/pull/541) that the examples were updated to show drop-detection. I don't see that either.

**Comment by datoslabs** [comment]
Check in master branch example.js.

**Comment by msueping** [comment]
> Check in master branch example.js.

You are correct. The example.js has that "onDropAreaMouse..." code. I was under the impression that when you said "...the latest version of the library addressed the issue...", that the **core** js code was changed (not just the example, which btw, is not what the demo site is running).

**Comment by datoslabs** [comment]
I apologize, I just realized the example.js hasn't been updated since I reported this issue and mistakenly assumed the issue has been addressed (it may still be but I don't know for certain without further testing).  Using `onDrop` should still work for your use case.
