### ISSUE TITLE
Draggable interfering with contentEditable Div

### ISSUE THREAD

**Issue by javismiles** [react-grid-layout/react-draggable#598]
Hi, when I apply 
`<Draggable {...dragHandlers} >`
to a div that contains a text, the dragging works well. 
When I double click on the div, the text can be edited (contentEditable). However, because of the draggable component, the text in the div cannot be selected and also the cursor always appears at the beginning of the text and cannot be set in any other character by clicking (only using the keyboard keys so in touch devices doenst work)

how can I allow that functionality to work well whenever the user is not dragging and is editing the text of the div?
thank you

**Comment by javismiles** [comment]
could I for example set the element programmatically to be draggable or not with a similar line to "..draggable = false;", if I Could then I could disable it when user is editing and re-enable it otherwise

**Comment by STRML** [comment]
Surely you could - another suggestion would be to use the `handle` prop.

It doesn't really make sense to have editable or selectable text that also drags the div - when the user clicks and moves the mouse, what should happen? Should the grid element move, or the (editable) text be highlighted? So - you need to disambiguate it and tell the library that the text is not draggable.

**Comment by javismiles** [comment]
thank you very much for the reply
- when the user clicks and moves the mouse the div should drag
- when the user double clicks the div, it enters into editing mode and then contentEditable becomes active and user can edit the text
- when clicking outside element or on background, editing mode exits and all goes back to normal

I have now used the "disabled" prop to active and deactivate the dragging when being or not being in editing mode and it sort of works

what about the -handle- prop, how could that one help me? thank you :)

**Comment by javismiles** [comment]
I read
"// Specifies a selector to be used as the handle that initiates drag.
// Example: '.handle'
handle: string,"

but I dont understand how that could help, how would I use that handle prop to help in this case? thank you :)

**Comment by javismiles** [comment]
I understood it now thank you

**Comment by emaborsa** [comment]
@javismiles Have the same issue, how did you solve it?
