### ISSUE TITLE
cursor position gets offset when scrolling

### ISSUE THREAD

**Issue by smussell** [react-grid-layout/react-draggable#60]
When you drag beyond the edge of the page and cause scrolling, the cursor moves away from the object.

![drag-issue](https://cloud.githubusercontent.com/assets/90569/7974157/2f49344a-0a13-11e5-9286-6b1bf6274800.gif)

**Comment by STRML** [comment]
Thanks. Will fix this.

**Comment by STRML** [comment]
Please try `master` in your app. It will be a day or two before the next release as I prepare some other changes.

**Comment by smussell** [comment]
Awesome, thanks.
