### ISSUE TITLE
overwriting z-index property

### ISSUE THREAD

**Issue by javismiles** [react-grid-layout/react-draggable#602]
Im trying to set a z-index value in a div that can be dragged, and the problem is that the module adds these classes "react-draggable react-draggable-dragged" automatically to the element, which seem to prevent me from putting the z-index i want, how can i manage to overwrite it?
thank you

**Comment by STRML** [comment]
Those classes don't prevent you from setting your own styles. Add your own classes or your own overriding css.

**Comment by javismiles** [comment]
thank you, closing this,
could you please help me with https://github.com/react-grid-layout/react-draggable/issues/603, Im really stuck with that one, thank you
