### ISSUE TITLE
Feature Request: "disabled" prop

### ISSUE THREAD

**Issue by EvHaus** [react-grid-layout/react-draggable#66]
Sometimes you want to wrap elements in a `<Draggable/>` definition but not have them draggable until some condition is met. Currently you have to do this via:

```
if (shouldBeDraggable) {
    return (
        <Draggable>
            <div />
        </Draggable>
    );
} else {
    return (
        <div/>
    );
}
```

This is highly verbose and requires handling of different children prop values. If would be nice if react-draggable supported a disabled prop which would allow me to do something like this:

```

return (
    <Draggable disabled={!shouldBeDraggable}>
        <div />
    </Draggable>
);
```

**Comment by STRML** [comment]
Good idea.

In the meantime, you can work around this by setting `handle=".foobar"`, where `.foobar` is a class that doesn't exist inside the element.

**Comment by STRML** [comment]
This is in `v1.0.0`.
