### ISSUE TITLE
Multitouch support?

### ISSUE THREAD

**Issue by brianfay** [react-grid-layout/react-draggable#67]
This may be a bit of a pipedream, but it would be great to support multi-touch devices by allowing multiple elements to be dragged simultaneously. 

Right now, when you try to drag two elements at the same time, one touchmove event seems to take over for both elements.

From what I can tell, this happens because event listeners for move events are attached to the document, rather than a specific element. This means that "handleDrag" is going to fire on any component that is currently dragging.

I tried hacking together a solution with this in handleDrag:
<code>if(e.target != React.findDOMNode(this)){console.log(e.target); return;} </code>

I also had to change getControlPosition to look for "targetTouches" instead of "touches"
<code>var position = (e.targetTouches && e.targetTouches[0]) || e;</code>

This does allow elements to be moved independently via touch, but unfortunately causes another issue. If you drag too quickly, you're out of the bounds of the element, so the move event doesn't fire and control of the element is lost.

So I guess the event listeners need to stay on the document. Maybe an alternative solution would be keeping track of which touch in the e.touches array corresponds to which component. That seems tricky, but if I can come up with a clean way to do it I'll put in a pull request.

**Comment by brianfay** [comment]
I read more into how touch events work, and according to [this W3C spec](http://www.w3.org/TR/touch-events/#touch-interface) they are supposed to be given unique identifiers.

Using this info, I wrote #68, which is working in Chrome for Android.

**Comment by STRML** [comment]
Thanks for the contribution.
