### ISSUE TITLE
Parent boundaries are offset when element is added after load

### ISSUE THREAD

**Issue by yaqubroli** [react-grid-layout/react-draggable#70]
I just want to say that react-draggable is very useful and easy to use. However, I have an issue when I use bounds="parent" and then add an element in after page load: the border for the parent is offset to the very top left corner of the page.

Demonstration: ![Dragging problem](http://zippy.gfycat.com/SecretMilkyDuckbillcat.gif)

**Comment by oliverlaz** [comment]
I had the same issue. Adding "position: relative" to the parent's css style solved the issue for me.
