### ISSUE TITLE
dragging on ios

### ISSUE THREAD

**Issue by enjoylife** [react-grid-layout/react-draggable#71]
When dragging on ios the browser continues to scroll. This behavior is visible on the demo page. Is there a way to disable scroll on touch start for mobile?

**Comment by mweststrate** [comment]
+1

**Comment by mweststrate** [comment]
You can partially solve this if I remember correctly by using `event.preventDefault()` in the Draggable onDrag event, but in that case you can now longer drag off the screen (which we also need)

**Comment by seansfkelley** [comment]
Depending on if you use the `axis` option or not, #47 may solve your issue.
