### ISSUE TITLE
Draggable Iframes

### ISSUE THREAD

**Issue by danielmayles** [react-grid-layout/react-draggable#78]
Hi just wondering what is the best way to make an Iframe draggable?

**Comment by STRML** [comment]
That's going to be very difficult because the iframe is going to be swallowing up your clicks. You may be able to put an overlay div over it and pass events down. Try `<DraggableCore>`, now in 1.0.

**Comment by paulius005** [comment]
You can also add `pointer-events: none;` to the iframe and that should do the trick as well
