### ISSUE TITLE
var root is undefined

### ISSUE THREAD

**Issue by t-kelly** [react-grid-layout/react-draggable#79]
`var root = typeof window !== 'undefined' ? window : this;` in `draggable.js` line 7

For some reason `this` is returning undefined for my setup. Things seem to work if I assign a new object `{}` instead. Is there any reason `this` has to be used?

**Comment by STRML** [comment]
What version are you using?

**Comment by t-kelly** [comment]
Using what is included int he React Material UI package.json - "react-draggable2": "^0.5.1"

**Comment by STRML** [comment]
That's the first I've seen `react-draggable2` - looks like somebody forked this project for some reason. You will have to bring up this issue on that repository.

https://github.com/mikepb/react-draggable

**Comment by t-kelly** [comment]
Doh - True. Sorry, misread this. Assumed it was referencing the main repo.

Thanks!
