### ISSUE TITLE
Please, use translate3d instead of translate

### ISSUE THREAD

**Issue by ezsper** [react-grid-layout/react-draggable#81]
I'm using this on a mobile app, `translate` is very slow as it don't make use of the GPU, you can just make a 3d option available, I'm forking it just for this. This is a great plugin, it will fit my needs with this option.

**Comment by misha-panyushkin** [comment]
+1

**Comment by ezsper** [comment]
A quick fix without the need to forking it, not a pretty one, but do the trick and I'm using it. Just create a new file with the code above, and instead of importing `react-draggable` you import this file you've just created.

```
import React from 'react';
import Draggable from 'react-draggable';
import classNames from 'react-draggable/node_modules/classnames';

var browserPrefix = (function() {
  if (typeof window === 'undefined') return '';
  // Thanks David Walsh
  var styles = window.getComputedStyle(document.documentElement, ''),
  pre = (Array.prototype.slice
        .call(styles)
        .join('')
        .match(/-(moz|webkit|ms)-/) || (styles.OLink === '' && ['', 'o'])
      )[1];
  // 'ms' is not titlecased
  if (pre === 'ms') return pre;
  return pre.slice(0, 1).toUpperCase() + pre.slice(1);
})();

let assign = Object.assign;

function canDragX(draggable) {
  return draggable.props.axis === 'both' || draggable.props.axis === 'x';
}

function canDragY(draggable) {
  return draggable.props.axis === 'both' || draggable.props.axis === 'y';
}

function createCSSTransform(style) {
  // Replace unitless items with px
  var x = style.x + 'px';
  var y = style.y + 'px';
  var out = {transform: 'translate(' + x + ',' + y + ') translateZ(0)'};
  // Add single prefixed property as well
  if (browserPrefix) {
    out[browserPrefix + 'Transform'] = out.transform;
  }
  return out;
}

Object.assign(Draggable.prototype, {
  render() {
    // Create style object. We extend from existing styles so we don't
    // remove anything already set (like background, color, etc).
    var childStyle = this.props.children.props.style || {};

    // Add a CSS transform to move the element around. This allows us to move the element around
    // without worrying about whether or not it is relatively or absolutely positioned.
    // If the item you are dragging already has a transform set, wrap it in a <span> so <Draggable>
    // has a clean slate.

    var x = canDragX(this) ? this.state.clientX : this.props.start.x
      , y = canDragY(this) ? this.state.clientY : this.props.start.y;

    var transform = createCSSTransform({
      // Set left if horizontal drag is enabled
      x: x,
      // Set top if vertical drag is enabled
      y: y
    });

    // Workaround IE pointer events; see #51
    // https://github.com/mzabriskie/react-draggable/issues/51#issuecomment-103488278
    var touchHacks = {
      touchAction: 'none'
    };

    var style = assign({}, childStyle, transform, touchHacks);

    if(this.props.parseStyle) {
      this.props.parseStyle(style, this);
    }

    // Set zIndex if currently dragging and prop has been provided
    if (this.state.dragging && !isNaN(this.props.zIndex)) {
      style.zIndex = this.props.zIndex;
    }

    var className = classNames((this.props.children.props.className || ''), 'react-draggable', {
      'react-draggable-dragging': this.state.dragging,
      'react-draggable-dragged': this.state.dragged
    });

    // Reuse the child provided
    // This makes it flexible to use whatever element is wanted (div, ul, etc)
    return React.cloneElement(React.Children.only(this.props.children), {
      style: style,
      className: className,
      onMouseDown: this.onMouseDown,
      onTouchStart: this.onTouchStart,
      onMouseUp: this.handleDragEnd,
      onTouchEnd: this.handleDragEnd
    });
  }
});

export default Draggable;
```

**Comment by ezsper** [comment]
Note: I'm using `Object.assign`, you can add to your package https://github.com/sindresorhus/object-assign or you can use lodash or underscore to merge objects.

**Comment by STRML** [comment]
Can you verify that this actually helps? We closed a PR a while ago because the creator couldn't show that there was actually a performance difference.

https://github.com/mzabriskie/react-draggable/pull/74

**Comment by ezsper** [comment]
If you're using Draggable on desktop apps there's no problem with pure `translate`, but for mobile there's no other way, at least so far, basically adding `translateZ(0)` solves the problem as it forces the GPU, using translate and translateZ is basically the same as using translate3d, both forces the GPU by using 3d attributions on elements.

**Comment by STRML** [comment]
I'm aware of the issue, but have you tested it on modern mobile browsers? This was a problem back in 2012, but I believe mobile browsers have picked up on the issue and optimized the performance of `translate` so developers don't have to do these awful hacks.

**Comment by ezsper** [comment]
Yes, I tested, I just did an small Phonegap app last month using Reapp.IO on top of CrossWalk (I also tested in native WebViews), and I had to force GPU in most of my interactive elements by using 3d attributions instead of the common attributions, so they could run smoothly. Reapp.IO for its page transition and dragging is using matrix3d as a working around, but I don't know exactly why. Mobile WebView still restrict the GPU for battery saving so it's still necessary to do this trick.

**Comment by misha-panyushkin** [comment]
@STRML there is also a benefit for that situations when we are faced the "blurry" effect for draggable nodes in just "translate" case. But there is no such effect in "translate3d" case. Indeed, there is a known fact that 3d is faster: http://jsperf.com/translate3d-vs-xy/28

**Comment by STRML** [comment]
That test seems kind of bogus - not sure what the speed of setting CSS has to really do with the actual framerate of the transform. In any case I don't actually see a difference in translate vs translate3d. I'll have to try this out on a phone to be sure.

**Comment by misha-panyushkin** [comment]
"...there is also a benefit for that situations when we are faced the "blurry" effect for draggable nodes in just "translate" case." - this is one more reason to use 3d.

**Comment by STRML** [comment]
@misha-panyushkin That's usually the other way around - the blurriness is caused _by_ putting the element on the GPU, not by keeping it off it. The GPU transforms the layer to a texture from a vector, which on certain pipelines can cause a loss of fidelity. I am not sure if you ran your test correctly, but I would be happy to see a comparison if you have one.

**Comment by STRML** [comment]
You could use `<DraggableCore>` to achieve this, or extend `<Draggable>` using ES6 classes and override `render()`.

Until there is a compelling test case you can show me to use 3d, I'd rather avoid the GPU compositing as it is known to cause issues (dGPU switching on Macbooks, battery life decreases, fuzzy text).

Please reopen if you have more information for me.
