### ISSUE TITLE
Right click on a draggable followed by right click elsewhere moves item

### ISSUE THREAD

**Issue by grassick** [react-grid-layout/react-draggable#82]
Makes for very strange effects when opening a context menu. Items should not be moved, I believe, by a series of right-clicks.

**Comment by jetpacmonkey** [comment]
I came across the same annoyance. Just in case the maintainer decides not to add this, you could do it yourself using the `onStart` prop.

``` jsx
onStart={function(event) {
    if (event.button !== 0) {
        return false;
    }
}}
```

**Comment by STRML** [comment]
I don't want to hardcode this into the library - you might want to override this - but it may make sense to put in `<Draggable>` and not `<DraggableCore>`, as users wanting really custom functionality will use Core.
