### ISSUE TITLE
Dragging SVG elements in IE (any version)

### ISSUE THREAD

**Issue by psaia** [react-grid-layout/react-draggable#83]
At the moment I don't have a jsfiddle setup, but it appears that the dragging of SVG elements has no effect in any version of Internet Explorer. I can't think of any obvious reason why this would be because `translate` works just fine in IE on SVG. It seems to have something to do with the onDrag event listeners.

**Comment by martinRoss** [comment]
I can confirm this issue. It is a known [bug in IE](https://connect.microsoft.com/IE/feedback/details/811744/ie11-bug-with-implementation-of-css-transforms-in-svg).

A fix would require detecting if a node is an Instance of SVGElement and using the transform attribute; not the style transform property. If I find some spare time I'll try to write a patch.

**Comment by martinRoss** [comment]
@petesaia Haven't had a chance to write tests and put in a pull request but I have fix here - https://github.com/martinRoss/react-draggable

I was hoping to intelligently detect if the child nodes were of type SVGElement but it does not look like there is a reliable way to do that; particularlly when an SVG is created without a namespace. Instead, you'll have to set `isSVG={true}` if you are using this with an SVG element. Chrome and Firefox respect the transform property so this shouldn't break anything for you.

**Comment by psaia** [comment]
Man, that's awesome. Thanks a lot @martinRoss!

**Comment by psaia** [comment]
Would be great to get this merged.

**Comment by psaia** [comment]
I guess the main issue is that it can't be used simple by adding

`"react-bootstrap": "https://github.com/mzabriskie/react-draggable.git"`

to the package.

**Comment by martinRoss** [comment]
@petesaia Just wrote some tests and submitted a pull request. Hopefully this will make it into master soon!

**Comment by psaia** [comment]
I hope so too @martinRoss! Thanks again, really.

**Comment by psaia** [comment]
Is there anything else I can do to move this along? Sorry, i'm on a project that's sort of pressing. Perhaps share the fix?

**Comment by martinRoss** [comment]
@petesaia I found a way to autodetect this instead of using a prop (the original pull request). I will try to write tests tonight and put in a new pull request. If it doesn't get merged soon I can work with you to get it working on your project.

**Comment by STRML** [comment]
@martinRoss Thanks, I would appreciate the PR.

**Comment by martinRoss** [comment]
@STRML I just put in a new pull request (now internally detecting if an element is an instanceof SVGElement) Let me know if there's anything else I can do!

**Comment by STRML** [comment]
Fixed in `0.8.4`, thanks @martinRoss .

**Comment by martinRoss** [comment]
Glad to help.
