### ISSUE TITLE
onDrag reports previous position

### ISSUE THREAD

**Issue by tf** [react-grid-layout/react-draggable#84]
[`onDrag` is called](https://github.com/mzabriskie/react-draggable/blob/master/lib/draggable.js#L611) before updating the state. It therefore reports positions which correspond to the previous mouse event. I am trying to update the position of a sibling in the `onDrag` handler. This behavior causes the sibling to "lag" behind.

Even worse, since [`handleDragEnd` resets the state](https://github.com/mzabriskie/react-draggable/blob/master/lib/draggable.js#L573) before calling `onStop`, the last position is never reported. This could lead to persisting different a position than last displayed.

I could think of three possible solutions:
- Set state before invoking `onDrag`. This would result in an extra render even if dragging is canceled. Not sure if this could have unwanted side effects.
- Explicitly pass the new position to `createUIEvent` and make it fall back to state if non is passed.
- Add a new event callback (`onDragged`?) to keep everything 100% backwards compatible. I can't help but feel that would be ugly, though.

I'd be happy to provide a PR.

**Comment by STRML** [comment]
This is fixed in `v1.0.0`, where we pass the event along from `<DraggableCore>` to the `onDrag` handler. This core event contains the correct data and is not out of date.
