### ISSUE TITLE
Multi-touch support

### ISSUE THREAD

**Issue by nickretallack** [react-grid-layout/react-draggable#85]
Try dragging two elements at once on a touch screen device.  It doesn't work right.  The second element starts moving, but its movement is correlated with the first element instead of moving on its own with the second finger.

**Comment by brianfay** [comment]
I wrote #68 for this a while back, which was accepted and merged in. I think the version in npm and in the demo haven't been updated in a while, because @STRML has been working on a major refactor (coreRefactor branch)

**Comment by STRML** [comment]
This is in `v1.0.0`.

**Comment by nickretallack** [comment]
I still don't see it in the example.
