### ISSUE TITLE
Programmatically trigger a drag start?

### ISSUE THREAD

**Issue by jetpacmonkey** [react-grid-layout/react-draggable#89]
Is it possible to make a draggable component start following the mouse on, say, a button click? I'm imagining that a click, which would obviously contain a mouseup event, would be how the item got placed in this case.

**Comment by STRML** [comment]
This isn't possible, even in `v1.0.0` with `<DraggableCore>` because the event will cancel on mouseUp. You may want to fork to do this - I don't consider this within the scope of Draggable. A simple component that basically tracks mouse movement and sets an absolute position would do the trick.

**Comment by 0b01** [comment]
What's the status on this now?

**Comment by STRML** [comment]
Was there something unclear about the resolution?

**Comment by 0b01** [comment]
It is such a simple thing to do:

http://jsfiddle.net/maCmB/1/

This is my ReactGridLayout interface for the same effect but got hung up on the last step:

``` Javascript

handleAdd(e, type) {
  var _this = this;
  var name = 'n' + this.state.newCounter;

  var obj = {
    i: name,
    x: this.state.layouts['lg'].length * 2 % (this.state.cols || 12),
    y: 0,
    w: 2,
    h: 2
  };

  var newData = {};
  newData[name] = {type: type};

  this.setState({
    layouts: {
      lg: this.state.layouts['lg'].concat(obj),
    },
    newCounter: this.state.newCounter + 1,
    data: Object.assign({}, this.state.data, newData),
  }, function(){
    var newGridItem = _this._grid.refs.rrgl.refs.rgl.state.griditems[name];
    // var newDomObj = _this._grid.refs.rrgl.refs.rgl.props.children.filter((c)=>c.key==name)[0];
    var newDomObj = ReactDOM.findDOMNode(newGridItem);
    var newEvent = new MouseEvent('mousemove', Object.assign({},{...e},{target: newDomObj}));
    console.log(newDomObj);
    newGridItem.onDragHandler('onDragStart')(newEvent, {node: newDomObj, deltaX: 0, deltaY: 0});
    newGridItem.onDragHandler('onDrag')(newEvent, {node: newDomObj, deltaX: 0, deltaY: 0});
  });

}
```

The error is `GridItem.js:300 Uncaught Error: onDrag called before onDragStart`
