### ISSUE TITLE
Options for alternate drag offset strategies

### ISSUE THREAD

**Issue by AndrewRayCode** [react-grid-layout/react-draggable#92]
This is similar to [#81](https://github.com/mzabriskie/react-draggable/issues/81). I'm using draggable in an SVG context, and using `translate()` actually gets in the way, using `x` and `y` attrs would be better. In my specific case I can pan and zoom my canvas, as well as drag the elements on it. Getting element positions is now more complicated because there's the transform matrix applied to the top level node, and a second transform applied to the dragged item itself. This makes it harder to reason about the application and harder to do math to find local vs world coords, etc. If I could drag using x and y which works in SVG (or specify any other offset strategy) I would have a much easier time

**Comment by STRML** [comment]
You can do this yourself with `<DraggableCore>` and do any offset strategy you like.

SVG support is fixed in `v1.0.0`.
