### ISSUE TITLE
moveOnStartChange breaks drag position

### ISSUE THREAD

**Issue by AndrewRayCode** [react-grid-layout/react-draggable#94]
Check out the [associated PR](https://github.com/mzabriskie/react-draggable/pull/93) and open `example/index.html`. All it does is add `moveOnStartChange` to one drag element.

<img width="517" alt="broken" src="https://cloud.githubusercontent.com/assets/79215/10413254/3cca9d12-6f57-11e5-8b1b-1ccb507bf822.png">

You can see when you start dragging it the element jumps about 400 pixels down the page, not at the mouse coords, which I think is related to improperly handling/reading `clientX` and `clientY`. I was trying to implement a custom drag strategy to deal with my flux flow but it seems it's currently impossible because `moveOnStartChange` breaks dragging behavior.

**Comment by AndrewRayCode** [comment]
Here's what's going on:

When drag begins, `handleDragStart` is called. This sets `offsetX` to the correct position:

```
offsetX: dragPoint.clientX - this.state.clientX
```

However, if `moveOnStartChange` is set, then `getInitialState` is called:

```
componentWillReceiveProps: function(newProps) {
    this.setState(this.getInitialState(newProps));
```

Which conveniently overwrites `offsetX` to 0:

```
getInitialState: function (props) {
    ...
    return {
        offsetX: 0, offsetY: 0,
```

I'm not sure how this feature is supposed to work? You can't update the start position during a drag because it breaks the drag coordinates.

**Comment by STRML** [comment]
It really doesn't work well, and this is the impetus for
https://github.com/mzabriskie/react-draggable/tree/coreRefactor

**Comment by AndrewRayCode** [comment]
Fixed readme so users can avoid the several hours of debugging I went through https://github.com/mzabriskie/react-draggable/pull/95

**Comment by mweststrate** [comment]
I run into the same (or similar) issue, the proper fix is (I think) to not
ignore start position changes while dragging, even when the flag is set.

As a work around, I now keep the `moveOnStartChange` of `false`, and
instead change the `key` of the draggable if I want a new x/y; a new key
results in a fresh draggable.  This isn't feasible in every scenario
though, as the key change has to come from the parent component. The
proposed work around in the readme works as well: call resetState() on a
ref to the draggable.

**Comment by STRML** [comment]
`moveOnStartChange` is gone in `v1.0.0`, use `<DraggableCore>` if you need more control.

**Comment by mweststrate** [comment]
Awesome! This separation will help a lot :)
