### ISSUE TITLE
handleDragEnd called twice for all drags

### ISSUE THREAD

**Issue by AndrewRayCode** [react-grid-layout/react-draggable#96]
Looks like because it's bound to the child:

```
  onMouseUp: this.handleDragEnd,
```

As well as the document:

```
    addEvent(document, dragEventFor.end, this.handleDragEnd);
```

**Comment by STRML** [comment]
This shouldn't actually happen, as there is a check on `this.state.dragging`.

The double binding (actually triple, including a binding to onTouchEnd) is necessary to catch all the ways the drag could end.
